LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/Canvas/Layer.js",LZR.HTML5.jsPath+"HTML5/util/MouseDropController.js"]);LZR.HTML5.Canvas.PenLayer=function(a){LZR.HTML5.Canvas.Layer.call(this,a);this.cav=a.cav;this.ctx=this.cav.getContext("2d");this.layerMgr=a.layerMgr;this.ctrl=new LZR.HTML5.Util.MouseDropController(this.cav);this.ctrl.noMid=!0;this.ctrl.noClick=!0;this.constant={};this.obj||this.clear()};LZR.HTML5.Canvas.PenLayer.prototype=LZR.createPrototype(LZR.HTML5.Canvas.Layer.prototype);
LZR.HTML5.Canvas.PenLayer.prototype._super=LZR.HTML5.Canvas.Layer.prototype;LZR.HTML5.Canvas.PenLayer.prototype.className="LZR.HTML5.Canvas.PenLayer";LZR.HTML5.Canvas.PenLayer.prototype.version="0.0.1";LZR.HTML5.Canvas.PenLayer.prototype.init=function(){this.constant.d=LZR.HTML5.Util.getDomPositionForDocument(this.cav)};
LZR.HTML5.Canvas.PenLayer.prototype.draw=function(a,c,b,d,f,e,h,g){g&&(this.cav.width=this.layerMgr.s.w,this.cav.height=this.layerMgr.s.h,this._super.draw.call(this,this.ctx,c,b,d,f,0,0))};LZR.HTML5.Canvas.PenLayer.prototype.clear=function(){this.obj=this.ctx.createImageData(this.layerMgr.max.w,this.layerMgr.max.h)};LZR.HTML5.Canvas.PenLayer.prototype.ctrlEnable=function(){this.ctrl.state===this.ctrl.STATE.UNABLE&&this.ctrl.enable(!1,!1,!0)};
LZR.HTML5.Canvas.PenLayer.prototype.ctrlDisable=function(){this.ctrl.state!==this.ctrl.STATE.UNABLE&&this.ctrl.disable()};
LZR.HTML5.Canvas.PenLayer.prototype.ctrlUpdate=function(){var a,c;if(this.ctrl.state===this.ctrl.STATE.LEFT)a=(this.ctrl.leftStart.x-this.ctrl.leftEnd.x)*this.layerMgr.s.scale(),c=(this.ctrl.leftStart.y-this.ctrl.leftEnd.y)*this.layerMgr.s.scale(),this.ctrl.leftStart=LZR.HTML5.Util.clone(this.ctrl.leftEnd),this.layerMgr.pan(a,c);else if(this.ctrl.state===this.ctrl.STATE.RIGHT){a=(this.ctrl.rightStart.x-this.constant.d.left)*this.layerMgr.s.scale();c=(this.ctrl.rightStart.y-this.constant.d.top)*this.layerMgr.s.scale();
var b=(this.ctrl.rightEnd.x-this.constant.d.left)*this.layerMgr.s.scale(),d=(this.ctrl.rightEnd.y-this.constant.d.top)*this.layerMgr.s.scale();this.ctrl.rightStart=LZR.HTML5.Util.clone(this.ctrl.rightEnd);this.lineByCtx(a,c,b,d)}else 0!==this.ctrl.wheelValue&&(b=-this.ctrl.wheelValue,this.ctrl.wheelValue=0,a=(this.ctrl.currentPage.x-this.constant.d.left)*this.layerMgr.s.scale(),c=(this.ctrl.currentPage.y-this.constant.d.top)*this.layerMgr.s.scale(),this.layerMgr.zoom(b,a,c))};
LZR.HTML5.Canvas.PenLayer.prototype.resize=function(){this.init()};LZR.HTML5.Canvas.PenLayer.prototype.point=function(a,c){if(0<=a&&a<=this.obj.width){var b=4*(c*this.obj.width+a);this.obj.data[b]=255;this.obj.data[b+3]=255}};
LZR.HTML5.Canvas.PenLayer.prototype.line=function(a,c,b,d){var f,e,a=Math.floor(a+this.layerMgr.s.left),c=Math.floor(c+this.layerMgr.s.top),b=Math.floor(b+this.layerMgr.s.left),d=Math.floor(d+this.layerMgr.s.top);e=b-a;d-=c;f=e/d;if(Math.abs(e)>Math.abs(d)){0<e?(b=0,d=e):(b=e,d=0);for(;b<=d;b++)this.point(a+b,Math.floor(c+b/f))}else if(0!==d){0<d?b=0:(b=d,d=0);for(;b<=d;b++)this.point(Math.floor(a+f*b),c+b)}};
LZR.HTML5.Canvas.PenLayer.prototype.lineByCtx=function(a,c,b,d){if(a!==b||c!==d)if(this.ctx.beginPath(),this.ctx.moveTo(a,c),this.ctx.lineTo(b,d),this.ctx.stroke(),a=this.ctx.getImageData(0,0,this.cav.width,this.cav.height),a.width===this.obj.width&&a.height===this.obj.height)this.obj=a;else for(var c=Math.floor(this.layerMgr.s.left)+Math.floor(this.layerMgr.s.top)*this.obj.width,c=4*c,b=0,d=4*(this.obj.width-a.width),f=0;f<a.height;f++){for(var e=0;e<a.width;e++)this.obj.data[c++]=a.data[b++],this.obj.data[c++]=
a.data[b++],this.obj.data[c++]=a.data[b++],this.obj.data[c++]=a.data[b++];c+=d}};
