LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/Canvas/Layer.js",LZR.HTML5.jsPath+"HTML5/util/MouseDropController.js"]);LZR.HTML5.Canvas.PenLayer=function(b){LZR.HTML5.Canvas.Layer.call(this,b);this.cav=b.cav;this.ctx=this.cav.getContext("2d");this.layerMgr=b.layerMgr;this.ctrl=new LZR.HTML5.Util.MouseDropController(this.cav);this.ctrl.noMid=!0;this.ctrl.noClick=!0;this.constant={};this.obj||this.clear()};LZR.HTML5.Canvas.PenLayer.prototype=LZR.createPrototype(LZR.HTML5.Canvas.Layer.prototype);
LZR.HTML5.Canvas.PenLayer.prototype._super=LZR.HTML5.Canvas.Layer.prototype;LZR.HTML5.Canvas.PenLayer.prototype.className="LZR.HTML5.Canvas.PenLayer";LZR.HTML5.Canvas.PenLayer.prototype.version="0.0.1";LZR.HTML5.Canvas.PenLayer.prototype.init=function(){this.constant.d=LZR.HTML5.Util.getDomPositionForDocument(this.cav)};
LZR.HTML5.Canvas.PenLayer.prototype.draw=function(b,a,c,d,e,f,h,g){g&&(g=this.layerMgr.s.scale(),this.cav.width=g*this.layerMgr.canvas.width,this.cav.height=g*this.layerMgr.canvas.height,a+=this.layerMgr.offset.left*(1-g),c+=this.layerMgr.offset.top*(1-g),this._super.draw.call(this,this.ctx,a,c,this.cav.width,this.cav.height,0,0))};
LZR.HTML5.Canvas.PenLayer.prototype.clear=function(){this.obj=this.ctx.createImageData(this.layerMgr.max.w+this.layerMgr.offset.left+this.layerMgr.offset.right,this.layerMgr.max.h+this.layerMgr.offset.top+this.layerMgr.offset.bottom)};LZR.HTML5.Canvas.PenLayer.prototype.ctrlEnable=function(){this.ctrl.state===this.ctrl.STATE.UNABLE&&this.ctrl.enable(!1,!1,!0)};LZR.HTML5.Canvas.PenLayer.prototype.ctrlDisable=function(){this.ctrl.state!==this.ctrl.STATE.UNABLE&&this.ctrl.disable()};
LZR.HTML5.Canvas.PenLayer.prototype.ctrlUpdate=function(){var b,a;a=this.layerMgr.s.scale();if(this.ctrl.state===this.ctrl.STATE.LEFT)b=(this.ctrl.leftStart.x-this.ctrl.leftEnd.x)*a,a*=this.ctrl.leftStart.y-this.ctrl.leftEnd.y,this.ctrl.leftStart=LZR.HTML5.Util.clone(this.ctrl.leftEnd),this.layerMgr.pan(b,a);else if(this.ctrl.state===this.ctrl.STATE.RIGHT){b=(this.ctrl.rightStart.x-this.constant.d.left)*a;var c=(this.ctrl.rightStart.y-this.constant.d.top)*a,d=(this.ctrl.rightEnd.x-this.constant.d.left)*
a;a*=this.ctrl.rightEnd.y-this.constant.d.top;this.ctrl.rightStart=LZR.HTML5.Util.clone(this.ctrl.rightEnd);this.lineByCtx(b,c,d,a)}else 0!==this.ctrl.wheelValue&&(c=-this.ctrl.wheelValue,this.ctrl.wheelValue=0,b=(this.ctrl.currentPage.x-this.constant.d.left-this.layerMgr.offset.left)*a,a*=this.ctrl.currentPage.y-this.constant.d.top-this.layerMgr.offset.top,this.layerMgr.zoom(c,b,a))};LZR.HTML5.Canvas.PenLayer.prototype.resize=function(){this.init()};
LZR.HTML5.Canvas.PenLayer.prototype.point=function(b,a){if(0<=b&&b<=this.obj.width){var c=4*(a*this.obj.width+b);this.obj.data[c]=255;this.obj.data[c+3]=255}};
LZR.HTML5.Canvas.PenLayer.prototype.line=function(b,a,c,d){var e,f;e=this.layerMgr.s.scale();b=Math.floor(b+this.layerMgr.s.left+this.layerMgr.offset.left*(1-e));a=Math.floor(a+this.layerMgr.s.top+this.layerMgr.offset.top*(1-e));c=Math.floor(c+this.layerMgr.s.left+this.layerMgr.offset.left*(1-e));d=Math.floor(d+this.layerMgr.s.top+this.layerMgr.offset.top*(1-e));f=c-b;d-=a;e=f/d;if(Math.abs(f)>Math.abs(d)){0<f?(c=0,d=f):(c=f,d=0);for(;c<=d;c++)this.point(b+c,Math.floor(a+c/e))}else if(0!==d){0<d?
c=0:(c=d,d=0);for(;c<=d;c++)this.point(Math.floor(b+e*c),a+c)}};
LZR.HTML5.Canvas.PenLayer.prototype.lineByCtx=function(b,a,c,d){if(b!==c||a!==d)if(this.ctx.beginPath(),this.ctx.moveTo(b,a),this.ctx.lineTo(c,d),this.ctx.stroke(),b=this.ctx.getImageData(0,0,this.cav.width,this.cav.height),b.width===this.obj.width&&b.height===this.obj.height)this.obj=b;else for(var a=this.layerMgr.s.scale(),a=Math.floor(this.layerMgr.s.left+this.layerMgr.offset.left*(1-a))+Math.floor(this.layerMgr.s.top+this.layerMgr.offset.top*(1-a))*this.obj.width,a=4*a,c=0,d=4*(this.obj.width-
b.width),e=0;e<b.height;e++){for(var f=0;f<b.width;f++)this.obj.data[a++]=b.data[c++],this.obj.data[a++]=b.data[c++],this.obj.data[a++]=b.data[c++],this.obj.data[a++]=b.data[c++];a+=d}};
