LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/Canvas/ThumbnailImg.js",LZR.HTML5.jsPath+"HTML5/util/MouseDropController.js"]);
LZR.HTML5.Canvas.Thumbnail=function(a){this.canvas=a;this.ctx=a.getContext("2d");this.imgs=[];this.count=0;this.direction=this.rows=1;this.height=this.width=100;this.offsetV=this.offsetU=0;this.paddingV=this.paddingU=10;this.max=this.position=0;this.boderWidth=4;this.boderColor="red";this.buff=20;this.index=-1;this.ctrl=new LZR.HTML5.Util.MouseDropController(this.canvas);this.alineState=0;this.wheelScale=3;this.wheelStyle=2;this.alineFrameNum=1;this.noBoder=!1};
LZR.HTML5.Canvas.Thumbnail.prototype.className="LZR.HTML5.Canvas.Thumbnail";LZR.HTML5.Canvas.Thumbnail.prototype.version="0.0.1";LZR.HTML5.Canvas.Thumbnail.prototype.init=function(){this.ctrl.state===this.ctrl.STATE.UNABLE&&(this.ctrl.noMid=!0,this.ctrl.noRight=!0,this.ctrl.clickTime=300,this.ctrl.autoClick=LZR.HTML5.Util.bind(this,this.click),this.ctrl.enable());this.ctx.lineWidth=this.boderWidth;this.ctx.strokeStyle=this.boderColor;this.calculateMax()};
LZR.HTML5.Canvas.Thumbnail.prototype.flush=function(){this.ctx.clearRect(0,0,this.canvas.width,this.canvas.height);var a,d,e,b,f,c,g=0;1===this.direction?(e=this.height+this.paddingV,f=this.canvas.width,c=this.width):2===this.direction&&(e=this.width+this.paddingV,f=this.canvas.height,c=this.height);d=c+this.paddingU;0>this.position?(a=0,b=-this.position):(a=Math.floor(this.position/d)*this.rows,b=this.position%d,b<c?b=-b:(a+=this.rows,b=this.paddingU-b+c));for(b+=this.offsetU;b<f&&a<this.count;){g+=
this.offsetV;for(c=0;c<this.rows;c++){var h=this.imgs[a];1===this.direction?this.beforeDraw(this,a,b,g,this.width,this.height):2===this.direction&&this.beforeDraw(this,a,g,b,this.width,this.height);if(h)for(var h=h.getLayers(),i=0;i<h.length;i++)1===this.direction?h[i].draw(this.ctx,b,g,this.width,this.height):2===this.direction&&h[i].draw(this.ctx,g,b,this.width,this.height);this.ctx.globalAlpha=1;1===this.direction?(!this.noBoder&&a===this.index&&this.ctx.strokeRect(b,g,this.width,this.height),
this.draw(this,a,b,g,this.width,this.height)):2===this.direction&&(!this.noBoder&&a===this.index&&this.ctx.strokeRect(g,b,this.width,this.height),this.draw(this,a,g,b,this.width,this.height));a++;if(a>=this.count)break;g+=e}g=0;b+=d}};LZR.HTML5.Canvas.Thumbnail.prototype.scroll=function(a){this.position+=a;this.position<-this.buff?this.position=-this.buff:this.position>this.max&&(this.position=this.max);this.alineState=1};
LZR.HTML5.Canvas.Thumbnail.prototype.ctrlUpdate=function(a){var d;a||(a=this.ctrl);if(a.state==a.STATE.LEFT)1===this.direction?d=a.leftStart.x-a.leftEnd.x:2===this.direction&&(d=a.leftStart.y-a.leftEnd.y),0!==d&&(a.leftStart=LZR.HTML5.Util.clone(a.leftEnd),this.scroll(d));else if(0!==a.wheelValue)switch(d=a.wheelValue*-this.wheelScale,a.wheelValue=0,this.wheelStyle){case 1:this.scroll(d);break;case 2:this.aline(d);break;case 3:this.select(this.index+d)}else this.aline()};
LZR.HTML5.Canvas.Thumbnail.prototype.calculateMax=function(){var a=Math.ceil(this.count/this.rows);1===this.direction?a=a*(this.width+this.paddingU)-this.canvas.width:2===this.direction&&(a=a*(this.height+this.paddingU)-this.canvas.height);0>a&&(a=0);this.max=a+=this.buff};LZR.HTML5.Canvas.Thumbnail.prototype.click=function(a,d){var e=LZR.HTML5.Util.getDomPositionForDocument(this.canvas),a=a-e.left,d=d-e.top,e=this.calculateIndex(a,d).index;e!==this.index&&(this.index=e,this.onchange(e));this.onclick(e)};
LZR.HTML5.Canvas.Thumbnail.prototype.calculateIndex=function(a,d){var e,b,f,c;1===this.direction?(e=this.width+this.paddingU,b=this.height+this.paddingV,f=this.position+a,c=d):2===this.direction&&(e=this.height+this.paddingU,b=this.width+this.paddingV,f=this.position+d,c=a);f=Math.floor(f/e);c=Math.floor(c/b);c>=this.rows&&(c=this.rows-1);c+=f*this.rows;c>=this.count&&(c=this.count-1);return{d:e,t:b,i:f,index:c}};
LZR.HTML5.Canvas.Thumbnail.prototype.aline=function(a,d){isNaN(a)||(this.alineState=1);if(1===this.alineState){this.alineState=2;var e=this.ctrl.state!==this.ctrl.STATE.UNABLE;this.ctrlDisable();var b,f;0>this.position?b=0:(f=this.calculateIndex(0,0),b=f.i*f.d,this.position-b>f.d/2&&(b+=f.d));isNaN(a)||(b=d?f.d*Math.floor(a/this.rows):b+f.d*a);0>=b?(b=0,this.position<=b&&(this.position=-this.buff)):b>this.max&&(b=this.max-this.buff,this.position>=b&&(this.position=this.max));this.alineShow(b,this.alineFrameNum,
0,20,e)}};LZR.HTML5.Canvas.Thumbnail.prototype.alineShow=function(a,d,e,b,f){var c=d-e;1>=c?(this.position=a,this.flush(),this.alineState=0,f&&this.ctrlEnable()):(c=Math.floor((a-this.position)/c),0===c?(this.position=a,this.flush(),this.alineState=0,f&&this.ctrlEnable()):(this.position+=c,this.flush(),e++,setTimeout(LZR.HTML5.Util.bind(this,this.alineShow,a,d,e,b,f),b)))};
LZR.HTML5.Canvas.Thumbnail.prototype.select=function(a){this.index!==a&&(a>=this.count?a=this.count-1:0>a&&(a=0),this.index=a,this.aline(a,!0),this.onchange(a))};LZR.HTML5.Canvas.Thumbnail.prototype.ctrlEnable=function(){this.ctrl.state===this.ctrl.STATE.UNABLE&&this.ctrl.enable()};LZR.HTML5.Canvas.Thumbnail.prototype.ctrlDisable=function(){this.ctrl.state!==this.ctrl.STATE.UNABLE&&this.ctrl.disable()};
LZR.HTML5.Canvas.Thumbnail.prototype.resize=function(){var a=this.ctx.font;LZR.HTML5.Util.mateWidth(this.canvas);this.init();this.ctx.font=a};LZR.HTML5.Canvas.Thumbnail.prototype.loadImg=function(){};LZR.HTML5.Canvas.Thumbnail.prototype.onchange=function(){};LZR.HTML5.Canvas.Thumbnail.prototype.onclick=function(){};LZR.HTML5.Canvas.Thumbnail.prototype.draw=function(){};LZR.HTML5.Canvas.Thumbnail.prototype.beforeDraw=function(){};
