LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/util/Layout/GridElement.js",LZR.HTML5.jsPath+"HTML5/util/Event.js"]);
LZR.HTML5.Util.Layout.GridLayout=function(a){a.type=0;LZR.HTML5.Util.Layout.BaseDiv.call(this,a);this.minWidth=a.minWidth?a.minWidth:100;this.maxWidth=a.maxWidth?a.maxWidth:this.minWidth;this.minNum=a.minNum?a.minNum:1;this.maxNum=a.maxNum?a.maxNum:this.minNum;this.wMargin=a.wMargin?a.wMargin:0;this.hMargin=a.hMargin?a.hMargin:0;this.maxMargin=a.maxMargin?a.maxMargin:this.wMargin;this.ratio=a.ratio?a.ratio:1;this.u=this.w=this.n=-1;this.rows=[];LZR.HTML5.Util.Event.addEvent(window,"resize",LZR.bind(this,
this.init),!1)};LZR.HTML5.Util.Layout.GridLayout.prototype=LZR.createPrototype(LZR.HTML5.Util.Layout.BaseDiv.prototype);LZR.HTML5.Util.Layout.GridLayout.prototype._super=LZR.HTML5.Util.Layout.BaseDiv.prototype;LZR.HTML5.Util.Layout.GridLayout.prototype.className="LZR.HTML5.Util.Layout.GridLayout";LZR.HTML5.Util.Layout.GridLayout.prototype.version="0.0.1";
LZR.HTML5.Util.Layout.GridLayout.prototype.init=function(){this.outDiv&&this.delChild(this.outDiv);var a=this.div.scrollWidth,c=(a+this.wMargin)/(this.minWidth+this.wMargin),c=Math.floor(c);c<this.minNum?c=this.minNum:c>this.maxNum&&(c=this.maxNum);var d=0,a=(a-(c-1)*this.wMargin)/c;a>this.maxWidth?(d=a-this.maxWidth,a=this.maxWidth):a<this.minWidth&&(a=this.minWidth);d+=this.wMargin;d>this.maxMargin&&(d=this.maxMargin);var l=a*this.ratio,j=this.hMargin;if(this.n!==c||this.w!=a||this.u!=d){this.outDiv=
new LZR.HTML5.Util.Layout.BaseDiv(0);this.outDiv.div.style.textAlign="center";this.outDiv.placeTo(this.div);this.w=a;this.u=d;this.n!==c&&(this.n=c,this.rows=this.calcLayout(c,this.children));for(var h,m=c*(a+d)-d,c=0;c<this.rows.length;c++){var i=this.rows[c],e=new LZR.HTML5.Util.Layout.BaseDiv(0),b=e.div.style;b.width=m+"px";b.height=l+"px";b.marginLeft="auto";b.marginRight="auto";0<c&&(b=new LZR.HTML5.Util.Layout.BaseDiv(0),b.div.style.height=j+"px",this.outDiv.addChild(b));this.outDiv.addChild(e);
var f,g=0;for(h=0;h<i.length;h++)0<h&&(g+=d),0>i[h]?g+=a:(g&&(f=new LZR.HTML5.Util.Layout.BaseDiv(0),b=f.div.style,b.width=g+"px",b.height="1px",b.display="inline-block",b.verticalAlign="top",e.addChild(f),g=0),f=this.children[i[h]],b=f.div.style,b.width=a*f.w+d*(f.w-1)+"px",b.height=l*f.h+j*(f.h-1)+"px",b.display="inline-block",b.verticalAlign="top",f.placeTo(e.div),h+=f.w-1);g&&(f=new LZR.HTML5.Util.Layout.BaseDiv(0),b=f.div.style,b.width=g+"px",b.height="1px",b.display="inline-block",b.verticalAlign=
"top",e.addChild(f))}}else this.outDiv.placeTo(this.div)};LZR.HTML5.Util.Layout.GridLayout.prototype.calcLayout=function(a,c){for(var d,l=0,j=[],h=0;h<c.length;h++)d=c[h],d.w=d.width>a?a:d.width,d.h=d.height,l=this.calcRows(j,a,d.w,d.h,l,h);return j};LZR.HTML5.Util.Layout.GridLayout.prototype.createRow=function(a){for(var c=[],d=0;d<a;d++)c.push(-1);c.p=0;return c};
LZR.HTML5.Util.Layout.GridLayout.prototype.calcRows=function(a,c,d,l,j,h){for(var m=!0,i=j;i<a.length;i++){var e=a[i],b=0;if(e.p===c)m&&j++;else for(var m=!1,f=0;f<c;f++)if(-1===e[f]){if(b++,b===d){var b=f-d+1,g,k=!0;for(g=1;g<l;g++)if(a[i+g]&&-1!==a[i+g][b]){k=!1;b=0;break}if(k){e.p+=d;e[b]=h;for(k=1;k<d;k++)e[b+k]=-2;for(g=1;g<l;g++){e=a[i+g];e||(e=this.createRow(c),a.push(e));e.p+=d;for(k=0;k<d;k++)e[b+k]=-3}return j}}}else b=0}a.push(this.createRow(c));this.calcRows(a,c,d,l,i,h);return j};
LZR.HTML5.Util.Layout.GridLayout.prototype.addChild=function(a){"LZR.HTML5.Util.Layout.GridElement"===a.className&&this._super.addChild.call(this,a,!0)};LZR.HTML5.Util.Layout.GridLayout.prototype.delChild=function(a){this._super.delChild.call(this,a)};
