LZR.HTML5.loadJs([LZR.HTML5.jsPath+"util/Graphics.js"]);LZR.Util.Graphics.Edge=function(a){this.reset(a);this.children=[];this.parent=null;this.parentIndex=-1};LZR.Util.Graphics.Edge.prototype.className="LZR.Util.Graphics.Edge";LZR.Util.Graphics.Edge.prototype.version="0.0.0";LZR.Util.Graphics.Edge.prototype.reset=function(a){this.top=a.top?a.top:0;this.left=a.left?a.left:0;this.w=a.width;this.h=a.height;this.r=this.w/this.h;this.baseW=this.w};
LZR.Util.Graphics.Edge.prototype.scale=function(){return this.w/this.baseW};LZR.Util.Graphics.Edge.prototype.right=function(){return this.left+this.w};LZR.Util.Graphics.Edge.prototype.bottom=function(){return this.top+this.h};LZR.Util.Graphics.Edge.prototype.reHeight=function(){this.h=this.w/this.r};LZR.Util.Graphics.Edge.prototype.move=function(a,b){this.left+=a;this.top+=b};LZR.Util.Graphics.Edge.prototype.zoom=function(a,b,c){this.w*=a;this.h*=a;this.move(b-a*b,c-a*c)};
LZR.Util.Graphics.Edge.prototype.addChild=function(a,b){a.parent&&a.delParent();a.parent=this;b?(a.parentIndex=b,this.children.splice(indec,0,a)):(a.parentIndex=this.children.length,this.children.push(a))};LZR.Util.Graphics.Edge.prototype.delChild=function(a){return this===a.parent?(this.children.splice(a.parentIndex,1),a.parent=null,a.parentIndex=-1,!0):!1};LZR.Util.Graphics.Edge.prototype.setParent=function(a,b){a.addChild(this,b)};
LZR.Util.Graphics.Edge.prototype.delParent=function(){this.parent&&this.parent.delChild(this)};LZR.Util.Graphics.Edge.prototype.positionByParent=function(a){if(!a&&(a=this.parent,!a))return!1;var b=0;this.top<a.top?this.top=a.top:(b=a.bottom()-this.bottom(),0>b&&(this.top+=b));this.left<a.left?this.left=a.left:(b=a.right()-this.right(),0>b&&(this.left+=b))};
LZR.Util.Graphics.Edge.prototype.rrByParent=function(a){if(!a&&(a=this.parent,!a))return!1;if(this.r<a.r){if(this.h>a.h)return this.h=a.h,this.w=this.r*this.h,!0}else if(this.w>a.w)return this.w=a.w,this.h=this.w/this.r,!0;return!1};LZR.Util.Graphics.Edge.prototype.rrByChild=function(a){if(!a&&(a=this.children[0],!a))return!1;if(this.r<a.r){if(this.h<a.h)return this.h=a.h,this.w=this.r*this.h,!0}else if(this.w<a.w)return this.w=a.w,this.h=this.w/this.r,!0;return!1};
LZR.Util.Graphics.Edge.prototype.moveInParent=function(a,b,c){this.move(a,b);this.positionByParentInContain(c)};LZR.Util.Graphics.Edge.prototype.zoomInParent=function(a,b,c,f,g){var d=b/this.w,e=c/this.h;this.w*=a;this.h*=a;1<a?this.rrByParent(f):1>a&&this.rrByChild(g);d*=this.w;e*=this.h;this.move(b-d,c-e);1<a&&this.positionByParentInContain(f)};LZR.Util.Graphics.Edge.prototype.floor=function(){this.top=Math.floor(this.top);this.left=Math.floor(this.left);this.w=Math.floor(this.w);this.h=Math.floor(this.h)};
LZR.Util.Graphics.Edge.prototype.alineInParent=function(a,b){if(!b&&(b=this.parent,!b))return!1;switch(a){case "center":this.left=(b.w-this.w)/2;this.top=(b.h-this.h)/2;break;default:return!1}return!0};
LZR.Util.Graphics.Edge.prototype.positionByParentInContain=function(a){if(!a&&(a=this.parent,!a))return!1;var b=0;this.r<a.r?(this.left<a.left?this.left=a.left:(b=a.right()-this.right(),0>b&&(this.left+=b)),this.h>a.h?this.top=(a.h-this.h)/2:this.top<a.top?this.top=a.top:(b=a.bottom()-this.bottom(),0>b&&(this.top+=b))):(this.top<a.top?this.top=a.top:(b=a.bottom()-this.bottom(),0>b&&(this.top+=b)),this.w>a.w?this.left=(a.w-this.w)/2:this.left<a.left?this.left=a.left:(b=a.right()-this.right(),0>b&&
(this.left+=b)))};LZR.Util.Graphics.Edge.prototype.rrByParentInContain=function(a){if(!a&&(a=this.parent,!a))return!1;if(this.r<a.r){if(this.w>a.w)return this.w=a.w,this.h=this.w/this.r,!0}else if(this.h>a.h)return this.h=a.h,this.w=this.r*this.h,!0;return!1};LZR.Util.Graphics.Edge.prototype.zoomInParentInContain=function(a,b,c,f,g){var d=b/this.w,e=c/this.h;this.w*=a;this.h*=a;1<a?this.rrByParentInContain(f):1>a&&this.rrByChild(g);d*=this.w;e*=this.h;this.move(b-d,c-e);1<a&&this.positionByParentInContain(f)};
