window.ol||(LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/expand/ol3/ol.js"]),LZR.HTML5.loadCss([LZR.HTML5.jsPath+"HTML5/expand/ol3/ol.css"]));LZR.HTML5.loadJs([LZR.HTML5.jsPath+"util/Graphics.js"]);
LZR.HTML5.Bp.OpenLayers.Orbit=function(a){a.map&&(this.map=a.map,this.clrStr={"0":"245,255,255","3.5":"210,255,255","7.0":"190,255,255","10.5":"150,243,255","14.0":"131,232,255","17.5":"74,221,255","21.0":"26,212,255","24.5":"0,195,255","28.0":"0,202,255","31.5":"0,220,220","35.0":"0,232,190","39.0":"0,230,175","43.0":"0,230,140","47.0":"0,230,110","51.0":"0,230,80","55.0":"0,230,60","59.0":"0,230,50","63.0":"0,230,0","67.0":"30,230,0","71.0":"100,235,0","75.0":"180,240,0","79.0":"220,250,0","83.0":"255,255,0",
"87.0":"255,250,0","91.0":"255,245,0","95.0":"255,242,0","99.0":"255,240,0","103.0":"255,238,0","107.0":"255,235,0","111.0":"255,230,0","115.0":"255,220,0","118.5":"255,200,0","122.0":"255,190,0","125.5":"255,185,0","129.0":"255,180,0","132.5":"255,175,0","136.0":"255,170,0","139.5":"255,165,0","143.0":"255,145,0","146.5":"255,115,0","150.0":"255,95,0","160.0":"255,70,0","170.0":"255,20,0","180.0":"255,0,0","190.0":"245,0,0","200.0":"247,0,0","210.0":"249,0,0","220.0":"250,0,0","230.0":"252,0,0",
"240.0":"240,0,20","250.0":"240,0,50","260.0":"220,0,100","270.0":"200,0,145","280.0":"180,0,150","290.0":"160,0,150","300.0":"150,0,150","310.0":"140,0,160","320.0":"135,0,160","330.0":"130,0,160","340.0":"125,0,160","350.0":"120,0,160","10000.0":"110,0,160"},this.initData(a.data),this.sourceColor=a.sourceColor?a.sourceColor:"red",this.sourceSize=a.sourceSize?a.sourceSize:20,this.sourceWidth=a.sourceWidth?a.sourceWidth:2,this.sourceSpeed=a.sourceSpeed?a.sourceSpeed:0.01,this.orbitAnimationColor=
this.initColor(a.orbitAnimationColor),this.orbitShadowColor=this.initColor(a.orbitShadowColor),this.orbitColor=this.initColor(a.orbitColor),this.orbitBlur=a.orbitBlur?a.orbitBlur:20,this.orbitScale=a.orbitScale?a.orbitScale:0.5,this.orbitSpeed=a.orbitSpeed?a.orbitSpeed:0.01,this.nodeShadowColor=a.nodeShadowColor?a.nodeShadowColor:this.orbitShadowColor,this.nodeColor=a.nodeColor?a.nodeColor:this.orbitColor,this.nodeBlur=a.nodeBlur?a.nodeBlur:this.orbitBlur,this.nodeScale=a.nodeScale?a.nodeScale:3E3,
this.nodeMax=a.nodeMax?a.nodeMax:8,this.nodeMin=a.nodeMin?a.nodeMin:6,a.showNode?this.setShowNode(a.showNode):this.setShowNode(0),this.title=a.title?a.title:document.createElement("div"),this.titleArea=a.titleArea?a.titleArea:0,this.curentPosition=[-1,-1],this.nodeOverIndex=this.orbitOverIndex=-1,this.ctx=this.canvas=this.layer=null,this.gp=new LZR.Util.Graphics)};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.className="LZR.HTML5.Bp.OpenLayers.Orbit";LZR.HTML5.Bp.OpenLayers.Orbit.prototype.version="0.0.6";
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.initColor=function(a){var b=0,f=[];if(a){if("string"==LZR.HTML5.Util.getClassName(a)){for(b=0;b<this.data.length;b++)f.push(a);return f}f=a;b=f.length;isNaN(b)&&(b=0)}for(;b<this.data.length;b++)a="rgba("+Math.floor(255*Math.random())+", "+Math.floor(255*Math.random())+", "+Math.floor(255*Math.random())+", 1)",f.push(a);return f};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.init=function(){null===this.layer&&(this.layer=new ol.layer.Image({source:new ol.source.ImageStatic({url:"",imageExtent:[0,0,0,0]})}),this.map.on("pointermove",LZR.bind(this,function(a){this.curentPosition=a.pixel})),this.layer.on("postcompose",LZR.bind(this,function(){if(null===this.ctx){this.canvas=document.createElement("canvas");var a=this.map.getViewport();a.insertBefore(this.canvas,a.childNodes[1]);this.canvas.style.width="100%";this.canvas.style.height=
"100%";this.canvas.style.position="absolute";this.canvas.style.top="0";this.canvas.style.left="0";this.canvas.width=this.canvas.clientWidth;this.canvas.height=this.canvas.clientHeight;LZR.HTML5.Util.Event.addEvent(window,"resize",LZR.bind(this,function(){this.canvas.width=this.canvas.clientWidth;this.canvas.height=this.canvas.clientHeight}),!1);this.ctx=this.canvas.getContext("2d");a=this.title.style;a.visibility="hidden";a.position="relative";a=this.map.getTargetElement();a.appendChild(this.title);
this.mapW=a.scrollWidth;this.mapH=a.scrollHeight;this.mouseObi=this.titleNdi=this.titleObi=-1}this.flush(this.ctx)&&this.map.render()})),this.map.addLayer(this.layer))};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.flush=function(a){a.clearRect(0,0,this.canvas.width,this.canvas.height);var b=this.map.getView().getResolution();this.calcNodeWidth(b);for(var f=this.nodeOverIndex=this.orbitOverIndex=-1,c=0;c<this.data.length;c++)if(this.data[c].visible){var f=c,d=this.data[c].nodes;this.calcData(d,b);this.drawOrbitPath(d,a,c);this.calcNode(d,a,c);if(this.orbitOverIndex===c){if(this.drawNode(d,a,c),0<=this.nodeOverIndex&&(this.titleObi!==this.orbitOverIndex||this.titleNdi!==
this.nodeOverIndex)){this.titleObi=this.orbitOverIndex;this.titleNdi=this.nodeOverIndex;var e=this.title.style;e.left=this.curentPosition[0]+"px";e.top=this.curentPosition[1]-this.mapH+"px";this.onShowTitle(this.title,this.oldDat[this.titleObi].grdCollection[this.titleNdi],this.titleObi,this.titleNdi);"hidden"===e.visibility&&(e.visibility="visible")}}else this.ap[c]+=this.orbitSpeed,1<this.ap[c]&&(this.ap[c]=0);this.drawOrbit(d,a,c)}if(-1!==f){this.drawSource(a,f);-1!==this.titleNdi&&-1===this.nodeOverIndex&&
(this.onHidTitle(this.title,this.oldDat[this.titleObi].grdCollection[this.titleNdi],this.titleObi,this.titleNdi),this.titleNdi=this.titleObi=-1,this.title.style.visibility="hidden");if(-1===this.orbitOverIndex)-1!==this.mouseObi&&(this.onMouseOut(this.mouseObi),this.mouseObi=-1);else if(this.mouseObi!==this.orbitOverIndex){if(-1!==this.mouseObi)this.onMouseOut(this.mouseObi);this.onMouseOver(this.orbitOverIndex);this.mouseObi=this.orbitOverIndex}return!0}return!1};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.initData=function(a){this.oldDat=a;this.data=[];this.ap=[];if(a)for(var b=0;b<a.length;b++){var f={visible:!0};f.zlevel=a[b].zlevel;f.nodes=[];for(var c=a[b].grdCollection,d=0;d<c.length;d++){var e={},g;for(g in c[d])e[g]=c[d][g];e.lon=c[d].x;e.lat=c[d].y;if(0<d){var h=f.nodes[d-1],j=e.y-h.y,k=e.x-h.x;h.lineAngle=Math.asin(j/Math.sqrt(j*j+k*k));0>k&&(h.lineAngle=Math.PI-h.lineAngle)}c[d].values&&(e.fom={val:c[d].values[1],clr:this.getClrByStr(c[d].values[1])});
f.nodes.push(e)}this.data.push(f);this.ap.push(0)}};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.getClrByAQI=function(a){return 0>a?"rgba(0,0,0,0)":50>=a?"rgba(0,228,0,1)":100>=a?"rgba(255,255,0,1)":150>=a?"rgba(255,126,0,1)":200>=a?"rgba(255,0,0,1)":300>=a?"rgba(153,0,76,1)":500>=a?"rgba(126,0,35,1)":"rgba(0,0,0,0)"};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.getClrByStr=function(a){var b=null,f;for(f in this.clrStr){if(a<f)if(b)break;else return"rgba(0,0,0,0)";b=f}return"rgba("+this.clrStr[b]+",1)"};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcNodeWidth=function(a){this.nodeWidth=this.nodeScale/a;this.nodeWidth>this.nodeMax?this.nodeWidth=this.nodeMax:this.nodeWidth<this.nodeMin&&(this.nodeWidth=this.nodeMin)};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcData=function(a,b){for(var f=0,c=0;c<a.length;c++){var d=a[c],e=this.calcPixel(d.lon,d.lat);d.x=e[0];d.y=e[1];d.u=d.su/b*this.windScale;d.v=d.sv/b*this.windScale;if(0<c){var e=a[c-1],g=d.y-e.y,d=d.x-e.x;e.lineLong=Math.sqrt(g*g+d*d);e.lineAngle=Math.asin(g/e.lineLong);0>d&&(e.lineAngle=Math.PI-e.lineAngle);e.lineLong>f&&(f=e.lineLong)}}a.max=f};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawOrbitPath=function(a,b,f){var c=this.nodeWidth*this.orbitScale;b.save();b.fillStyle=this.orbitColor[f];b.shadowColor=this.orbitShadowColor[f];b.shadowBlur=this.orbitBlur;for(var d=0;d<a.length-1;d++){b.beginPath();var e=this.gp.calcTransform(a[d].lineAngle,1,1,a[d].x,a[d].y);b.setTransform(e[0],e[1],e[2],e[3],e[4],e[5]);b.moveTo(0,c);b.arc(0,0,c,Math.PI/2,3*Math.PI/2);b.lineTo(a[d].lineLong,-c);b.arc(a[d].lineLong,0,c,-Math.PI/2,Math.PI/2);b.closePath();
a[d].fom&&(e=b.createLinearGradient(0,0,a[d].lineLong,0),e.addColorStop(0,a[d].fom.clr),e.addColorStop(1,a[d+1].fom.clr),b.shadowBlur=0,b.fillStyle=e);b.fill()}b.restore();-1===this.orbitOverIndex&&b.isPointInPath(this.curentPosition[0],this.curentPosition[1])&&(this.orbitOverIndex=f)};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcNode=function(a,b,f){for(var c=this.nodeWidth+this.titleArea,d=2*Math.PI,e=0;e<a.length;e++)if(b.beginPath(),b.arc(a[e].x,a[e].y,c,0,d),(-1===this.orbitOverIndex||this.orbitOverIndex===f)&&b.isPointInPath(this.curentPosition[0],this.curentPosition[1])){this.orbitOverIndex=f;this.nodeOverIndex=e;break}};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawNode=function(a,b,f){var c=0,d=a.length;switch(this.showNode){case 1:c++;break;case 2:d--}var e=this.nodeWidth,g=2*Math.PI;b.save();b.fillStyle=this.nodeColor[f];b.shadowColor=this.nodeShadowColor[f];b.shadowBlur=this.nodeBlur;b.beginPath();for(f=c;f<d;f++)b.arc(a[f].x,a[f].y,e,0,g),b.closePath();b.fill();b.restore()};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawOrbit=function(a,b,f){b.save();b.fillStyle=this.orbitAnimationColor[f];b.beginPath();for(i=1;i<a.length;i++){var c=(a[i].x-a[i-1].x)*this.ap[f]+a[i-1].x,d=(a[i].y-a[i-1].y)*this.ap[f]+a[i-1].y,e=0.8*(a[i-1].lineLong/a.max);0.2>e&&(e=0.2);e*=this.nodeWidth;c=this.gp.calcTransform(a[i-1].lineAngle,e,e,c,d);b.setTransform(c[0],c[1],c[2],c[3],c[4],c[5]);b.moveTo(0,0);b.lineTo(-1,1);b.lineTo(3,0);b.lineTo(-1,-1);b.closePath()}b.fill();b.restore()};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawSource=function(a,b){var f,c,d;c=this.data[b].nodes;switch(this.showNode){case 2:d=c.length-1;f=c[d].x;c=c[d].y;0.05>this.apSource&&(this.apSource=1);break;default:f=c[0].x,c=c[0].y,1<this.apSource&&(this.apSource=0.05)}d=this.sourceSize*this.apSource;a.save();a.lineWidth=this.sourceWidth;a.strokeStyle=this.sourceColor;a.beginPath();a.arc(f,c,d,0,2*Math.PI);a.stroke();a.restore();this.apSource+=this.sourceSpeed};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.setVisible=function(a,b){var f=this.data[a];f&&(f.visible=b);b&&this.map.render()};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.setShowNode=function(a){this.showNode=a;2===this.showNode?(this.apSource=1,0<this.sourceSpeed&&(this.sourceSpeed*=-1)):(this.apSource=0,0>this.sourceSpeed&&(this.sourceSpeed*=-1))};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcPixel=function(a,b){return this.map.getPixelFromCoordinate(ol.proj.fromLonLat([a,b]))};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.onShowTitle=function(){};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.onHidTitle=function(){};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.onMouseOver=function(){};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.onMouseOut=function(){};
