LZR.HTML5.loadJs([LZR.HTML5.jsPath+"util/Date.js",LZR.HTML5.jsPath+"HTML5/util/Scroll.js"]);
LZR.HTML5.Util.BaseTimeAxis=function(a){this.startTime=this.calcStartTime(a.startTime);this.timeLong=a.timeLong?a.timeLong:100;this.timeStep=a.timeStep?1E3*a.timeStep:1E3;this.style=a.style?a.style:0;this.allShow=a.allShow?a.allShow:!1;this.noDrop=a.noDrop?a.noDrop:0;this.titleOver=a.titleOver?a.titleOver:0;this.hidTitle=a.hidTitle?a.hidTitle:!1;this.playStep=a.playStep?a.playStep:1;this.playSpeed=a.playSpeed?a.playSpeed:100;this.playMod=a.playMod?a.playMod:0;this.hoverTime=a.hoverTime?a.hoverTime:
1E3;this.nochange=!1;this.scroll=new LZR.HTML5.Util.Scroll({count:a.timeLong,position:0,direction:1,autoLen:0,padd:0,len:"100%",stripClass:a.backStripClass,btnClass:a.scrollBtnClass,div:a.div,noAuto:!0});this.scroll.onchange=LZR.bind(this,function(a){var b;switch(this.style){case 0:b=a;break;case 1:b=a+0.5}b=b/this.timeLong*this.scroll.len;this.cover.style.width=b+"px";this.currentTitle.style.left=b-parseFloat(this.currentTitle.scrollWidth,10)/2+"px";b=this.calcTimeByPosition(a);this.currentTitle.innerHTML=
this.getCurrentTitleContent(b);if(this.nochange)this.nochange=!1;else this.onchange(b,a)});this.div=this.scroll.div;this.cover=document.createElement("div");LZR.HTML5.Util.Css.addClass(this.cover,a.coverStripClass);var b=this.cover.style;b.width=0;this.scroll.strip.appendChild(this.cover);this.currentTitle=document.createElement("div");LZR.HTML5.Util.Css.addClass(this.currentTitle,a.currentTitleClass);b=this.currentTitle.style;b.position="relative";if(!this.allShow||this.hidTitle)b.visibility="hidden";
this.cover.appendChild(this.currentTitle);this.mouseTitle=document.createElement("div");LZR.HTML5.Util.Css.addClass(this.mouseTitle,a.mouseTitleClass);b=this.mouseTitle.style;b.position="relative";b.display="none";this.scroll.strip.appendChild(this.mouseTitle);this.mouseTile_top=parseFloat(this.getStyle(this.mouseTitle,"top"));this.ctrl=new LZR.HTML5.Util.MouseDropController(this.scroll.strip);this.ctrl.noMid=!0;this.ctrl.noRight=!0;this.ctrl.noClick=!0;this.ctrl.noCurrentMove=!1;this.hover=null;
this.ctrl.autoCurrentMove=LZR.bind(this,function(a,b){var e=this.calcPositionByMouse(a,b),c=a-this.scroll.constant.stripPs.left;if(0<c&&c<this.scroll.len){var f=parseFloat(this.mouseTitle.scrollWidth,10);this.mouseTitle.style.left=c-f/2+"px";if(this.titleOver){var c=parseFloat(this.mouseTitle.style.left,10),g=parseFloat(this.currentTitle.style.left,10);this.mouseTitle.style.top=c>g-f&&c<g+parseFloat(this.currentTitle.scrollWidth,10)?this.mouseTile_top+this.titleOver+"px":this.mouseTile_top+"px"}}this.mouseTitle.innerHTML=
this.getMouseTitleContent(this.calcTimeByPosition(e));clearTimeout(this.hover);this.hover=setTimeout(LZR.bind(this,function(a){this.onHover(this.calcTimeByPosition(a),a)},e),this.hoverTime)});a=LZR.bind(this,function(){this.ctrl.state===this.ctrl.STATE.LEFT&&(this.pause(),this.setPosition(this.calcPositionByMouse(this.ctrl.leftEnd.x,this.ctrl.leftEnd.y)),this.autoStop())});switch(this.noDrop){case 2:this.ctrl.autoMouseUp=LZR.bind(this,function(){if(this.ctrl.state===this.ctrl.STATE.LEFT){this.nochange=
!1;var a=this.getCurrentPosition();this.onchange(this.calcTimeByPosition(a),a)}});this.ctrl.autoFlush=LZR.bind(this,function(a){this.nochange=!0;a()},a);break;case 0:this.ctrl.autoFlush=a;break;case 1:this.ctrl.autoMouseUp=a}LZR.HTML5.Util.Event.addEvent(this.div,"mouseout",LZR.bind(this,function(){this.allShow||(this.currentTitle.style.visibility="hidden")}),!1);LZR.HTML5.Util.Event.addEvent(this.div,"mouseover",LZR.bind(this,function(){this.hidTitle||(this.currentTitle.style.visibility="visible")}),
!1);LZR.HTML5.Util.Event.addEvent(this.scroll.strip,"mouseout",LZR.bind(this,function(){this.mouseTitle.style.display="none";clearTimeout(this.hover)}),!1);LZR.HTML5.Util.Event.addEvent(this.scroll.strip,"mouseover",LZR.bind(this,function(){this.hidTitle||(this.mouseTitle.style.display="")}),!1)};LZR.HTML5.Util.BaseTimeAxis.prototype.className="LZR.HTML5.Util.BaseTimeAxis";LZR.HTML5.Util.BaseTimeAxis.prototype.version="0.0.2";
LZR.HTML5.Util.BaseTimeAxis.prototype.init=function(a){a&&(this.scroll.position=a);this.nochange=!0;this.scroll.init();this.ctrl.state===this.ctrl.STATE.UNABLE&&this.ctrl.enable(!1,!0,!0)};LZR.HTML5.Util.BaseTimeAxis.prototype.setPosition=function(a){this.scroll.setPosition(a)};
LZR.HTML5.Util.BaseTimeAxis.prototype.calcStartTime=function(a){switch(LZR.HTML5.Util.getClassName(a)){case "string":a=LZR.Util.Date.getDate(a).valueOf();break;case "Date":a=a.valueOf();break;case "number":break;default:a=new Date,a.setHours(0),a.setMinutes(0),a.setSeconds(0),a.setMilliseconds(0),a=a.valueOf()}return a};LZR.HTML5.Util.BaseTimeAxis.prototype.setTimeLong=function(a){this.timeLong=a;this.pause();this.scroll.srcObj.count=a;this.scroll.position=0;this.init()};
LZR.HTML5.Util.BaseTimeAxis.prototype.setAllShow=function(a){if((this.allShow=a)&&!this.hidTitle)this.currentTitle.style.visibility="visible"};LZR.HTML5.Util.BaseTimeAxis.prototype.setHidTitle=function(a){(this.hidTitle=a)?(this.currentTitle.style.visibility="hidden",this.mouseTitle.style.display="none"):this.allShow&&(this.currentTitle.style.visibility="visible")};LZR.HTML5.Util.BaseTimeAxis.prototype.setPlaySpeed=function(a){this.playSpeed=a;this.playHandle&&(this.pause(),this.play())};
LZR.HTML5.Util.BaseTimeAxis.prototype.next=function(){var a=this.getCurrentPosition()+this.playStep,b=!1;switch(this.style){case 0:b=a>this.timeLong;break;case 1:b=a>=this.timeLong}if(b)switch(this.playMod){case 0:a=0;break;case 1:return!1}this.setPosition(a);return!0};LZR.HTML5.Util.BaseTimeAxis.prototype.back=function(){var a=this.getCurrentPosition()-1;0>a&&(a=this.timeLong);this.setPosition(a)};
LZR.HTML5.Util.BaseTimeAxis.prototype.play=function(){this.playHandle||(this.playHandle=window.setInterval(LZR.bind(this,function(){this.next()||(this.stop(),this.autoStop())}),this.playSpeed))};LZR.HTML5.Util.BaseTimeAxis.prototype.pause=function(){this.playHandle&&(window.clearInterval(this.playHandle),this.playHandle=void 0)};LZR.HTML5.Util.BaseTimeAxis.prototype.stop=function(){this.pause();this.init(0)};LZR.HTML5.Util.BaseTimeAxis.prototype.getCurrentPosition=function(){return this.scroll.position};
LZR.HTML5.Util.BaseTimeAxis.prototype.getCurrentTime=function(){return this.calcTimeByPosition(this.scroll.position)};LZR.HTML5.Util.BaseTimeAxis.prototype.calcPositionByMouse=function(a){a=(a-this.scroll.constant.stripPs.left)/this.scroll.len*this.timeLong;if(0>a)a=0;else switch(this.style){case 0:a>this.timeLong&&(a=this.timeLong);break;case 1:a>=this.timeLong&&(a=this.timeLong-1)}return Math.floor(a)};LZR.HTML5.Util.BaseTimeAxis.prototype.calcPixByPosition=function(a){return a/this.timeLong*this.scroll.len};
LZR.HTML5.Util.BaseTimeAxis.prototype.calcTimeByPosition=function(a){return new Date(this.startTime+a*this.timeStep)};LZR.HTML5.Util.BaseTimeAxis.prototype.calcPositionByTime=function(a){return(a.valueOf()-this.startTime)/this.timeStep};LZR.HTML5.Util.BaseTimeAxis.prototype.getCurrentTitleContent=function(a){return LZR.HTML5.Util.format(a.getHours(),2,"0")+":"+LZR.HTML5.Util.format(a.getMinutes(),2,"0")};LZR.HTML5.Util.BaseTimeAxis.prototype.getMouseTitleContent=function(a){return this.getCurrentTitleContent(a)};
LZR.HTML5.Util.BaseTimeAxis.prototype.onchange=function(){};LZR.HTML5.Util.BaseTimeAxis.prototype.autoStop=function(){};LZR.HTML5.Util.BaseTimeAxis.prototype.onHover=function(){};LZR.HTML5.Util.BaseTimeAxis.prototype.getStyle=function(a,b){var d=window.getComputedStyle?window.getComputedStyle(a,null):obj.currentStyle;return b?d[b]:d};
