LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/util/Util.js",LZR.HTML5.jsPath+"HTML5/util/Event.js"]);
LZR.HTML5.Util.MouseDropController=function(a){this.ctrlDom=a?a:document;this.state=this.STATE.UNABLE;"\v"=="v"&&(this.STATE.LEFT=1,this.STATE.MID=4);this.defaultCursor=a.style.cursor;this.rightCursor=this.midCursor=this.leftCursor=null;this.currentPage={x:0,y:0};this.currentSelf={x:0,y:0};this.leftStart={x:0,y:0};this.leftEnd={x:0,y:0};this.midStart={x:0,y:0};this.midEnd={x:0,y:0};this.rightStart={x:0,y:0};this.rightEnd={x:0,y:0};this.wheelValue=0;this.noClick=this.noRight=this.noMid=this.noLeft=
!1;this.noCurrentMove=this.noLong=!0;this.clickTime=300;this.callbacks={wheel:null,mDown:null,mUp:null,mMove:null,mCurrentMove:null,click:null}};LZR.HTML5.Util.MouseDropController.prototype.className="LZR.HTML5.Util.MouseDropController";LZR.HTML5.Util.MouseDropController.prototype.version="0.0.5";LZR.HTML5.Util.MouseDropController.prototype.STATE={UNABLE:-2,NONE:-1,LEFT:0,MID:1,RIGHT:2,CLICK:101,LONG:102};
LZR.HTML5.Util.MouseDropController.prototype.enable=function(a,b,c){!b&&!this.callbacks.wheel&&(this.callbacks.wheel=LZR.HTML5.Util.addWheel(this.ctrlDom,LZR.HTML5.Util.bind(this,this.mouseWheel),!1));!a&&!this.callbacks.mDown&&(this.callbacks.mDown=LZR.HTML5.Util.addEvent(this.ctrlDom,"mousedown",LZR.HTML5.Util.bind(this,this.mouseDown),!1));!this.noCurrentMove&&!this.callbacks.mCurrentMove&&(this.callbacks.mCurrentMove=LZR.HTML5.Util.addEvent(this.ctrlDom,"mousemove",LZR.HTML5.Util.bind(this,this.mouseCurrentMove),
!1));(c||!this.noRight)&&LZR.HTML5.Util.addEvent(this.ctrlDom,"contextmenu",function(){LZR.HTML5.Util.stopDefault()},!1);this.state=this.STATE.NONE};
LZR.HTML5.Util.MouseDropController.prototype.disable=function(){this.callbacks.mCurrentMove&&(LZR.HTML5.Util.removeEvent(this.ctrlDom,"mousemove",this.callbacks.mCurrentMove,!1),this.callbacks.mCurrentMove=null);this.callbacks.mDown&&(LZR.HTML5.Util.removeEvent(this.ctrlDom,"mousedown",this.callbacks.mDown,!1),this.callbacks.mDown=null);this.callbacks.wheel&&(LZR.HTML5.Util.removeWheel(this.ctrlDom,this.callbacks.wheel,!1),this.callbacks.wheel=null);this.state=this.STATE.UNABLE};
LZR.HTML5.Util.MouseDropController.prototype.mouseWheel=function(a){LZR.HTML5.Util.stopDefault(a);LZR.HTML5.Util.stopBubble(a);this.noCurrentMove&&(this.currentPage=LZR.HTML5.Util.getMousePosition(a));this.wheelHandle(a.delta);this.autoFlush()};
LZR.HTML5.Util.MouseDropController.prototype.mouseDown=function(a){LZR.HTML5.Util.stopDefault(a);LZR.HTML5.Util.stopBubble(a);this.state==this.STATE.NONE&&(this.state=LZR.HTML5.Util.getEvent(a).button,this.callbacks.mMove=LZR.HTML5.Util.addEvent(document,"mousemove",LZR.HTML5.Util.bind(this,this.mouseMove),!1),this.callbacks.mUp=LZR.HTML5.Util.addEvent(document,"mouseup",LZR.HTML5.Util.bind(this,this.mouseUp),!1));a=LZR.HTML5.Util.getMousePosition(a);switch(this.state){case this.STATE.LEFT:this.noLeft||
this.leftStartHandle(a.x,a.y);this.noClick||(this.state=this.STATE.CLICK,this.callbacks.click=setTimeout(LZR.HTML5.Util.bind(this,function(){this.callbacks.click=null;this.state=this.noLong?this.STATE.LEFT:this.STATE.LONG}),this.clickTime));break;case this.STATE.MID:this.noMid||this.midStartHandle(a.x,a.y);break;case this.STATE.RIGHT:this.noRight||this.rightStartHandle(a.x,a.y)}this.autoMouseDown()};
LZR.HTML5.Util.MouseDropController.prototype.mouseMove=function(a){LZR.HTML5.Util.stopDefault(a);LZR.HTML5.Util.stopBubble(a);a=LZR.HTML5.Util.getMousePosition(a);switch(this.state){case this.STATE.CLICK:clearTimeout(this.callbacks.click),this.callbacks.click=null;case this.STATE.LONG:this.state=this.STATE.LEFT;case this.STATE.LEFT:this.noLeft||this.leftEndHandle(a.x,a.y);break;case this.STATE.MID:this.noMid||this.midEndHandle(a.x,a.y);break;case this.STATE.RIGHT:this.noRight||this.rightEndHandle(a.x,
a.y)}this.autoFlush()};LZR.HTML5.Util.MouseDropController.prototype.mouseCurrentMove=function(a){this.currentPage=a=LZR.HTML5.Util.getMousePosition(a);this.autoCurrentMove(a.x,a.y)};
LZR.HTML5.Util.MouseDropController.prototype.mouseUp=function(a){switch(this.state){case this.STATE.CLICK:p=LZR.HTML5.Util.getMousePosition(a);clearTimeout(this.callbacks.click);this.callbacks.click=null;this.autoClick(p.x,p.y);break;case this.STATE.LONG:p=LZR.HTML5.Util.getMousePosition(a),this.autoLong(p.x,p.y)}this.mouseMove(a);this.autoMouseUp();this.state=this.STATE.NONE;this.callbacks.mMove&&(LZR.HTML5.Util.removeEvent(document,"mousemove",this.callbacks.mMove,!1),this.callbacks.mMove=null);
this.callbacks.mUp&&(LZR.HTML5.Util.removeEvent(document,"mouseup",this.callbacks.mUp,!1),this.callbacks.mUp=null);this.ctrlDom.style.cursor!==this.defaultCursor&&(this.ctrlDom.style.cursor=this.defaultCursor)};LZR.HTML5.Util.MouseDropController.prototype.wheelHandle=function(a){this.wheelValue+=a};
LZR.HTML5.Util.MouseDropController.prototype.leftStartHandle=function(a,b){this.leftStart.x=a;this.leftStart.y=b;this.leftEnd=LZR.HTML5.Util.clone(this.leftStart);this.leftCursor&&(this.ctrlDom.style.cursor=this.leftCursor)};LZR.HTML5.Util.MouseDropController.prototype.leftEndHandle=function(a,b){this.leftEnd.x=a;this.leftEnd.y=b};
LZR.HTML5.Util.MouseDropController.prototype.midStartHandle=function(a,b){this.midStart.x=a;this.midStart.y=b;this.midEnd=LZR.HTML5.Util.clone(this.midStart);this.midCursor&&(this.ctrlDom.style.cursor=this.midCursor)};LZR.HTML5.Util.MouseDropController.prototype.midEndHandle=function(a,b){this.midEnd.x=a;this.midEnd.y=b};
LZR.HTML5.Util.MouseDropController.prototype.rightStartHandle=function(a,b){this.rightStart.x=a;this.rightStart.y=b;this.rightEnd=LZR.HTML5.Util.clone(this.rightStart);this.rightCursor&&(this.ctrlDom.style.cursor=this.rightCursor)};LZR.HTML5.Util.MouseDropController.prototype.rightEndHandle=function(a,b){this.rightEnd.x=a;this.rightEnd.y=b};LZR.HTML5.Util.MouseDropController.prototype.autoFlush=function(){};LZR.HTML5.Util.MouseDropController.prototype.autoMouseDown=function(){};
LZR.HTML5.Util.MouseDropController.prototype.autoMouseUp=function(){};LZR.HTML5.Util.MouseDropController.prototype.autoClick=function(){};LZR.HTML5.Util.MouseDropController.prototype.autoLong=function(){};LZR.HTML5.Util.MouseDropController.prototype.autoCurrentMove=function(){};
