LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/util/MouseDropController.js",LZR.HTML5.jsPath+"HTML5/util/Css.js"]);
LZR.HTML5.Util.Scroll=function(a){this.srcObj={};this.srcObj.count=a.count;this.position=a.position;this.autoLen=a.autoLen;this.autoMin=a.autoMin;this.hidTooBig=a.hidTooBig;this.direction=a.direction;this.srcObj.padd=a.padd;this.srcObj.len=a.len;this.strip=document.createElement("div");LZR.HTML5.Util.Css.addClass(this.strip,a.stripClass);a.div?(this.div=a.div,this.div.appendChild(this.strip)):this.div=this.strip;this.btn=document.createElement("div");this.btn.style.position="relative";LZR.HTML5.Util.Css.addClass(this.btn,
a.btnClass);this.strip.appendChild(this.btn);a.noAuto||(this.ctrlBtn=new LZR.HTML5.Util.MouseDropController(this.btn),this.ctrlBtn.noMid=!0,this.ctrlBtn.noRight=!0,this.ctrlBtn.noClick=!0,this.ctrlBtn.autoFlush=LZR.bind(this,this.ctrlUpdate,this.ctrlBtn),this.ctrlStrip=new LZR.HTML5.Util.MouseDropController(this.strip),this.ctrlStrip.noMid=!0,this.ctrlStrip.noRight=!0,this.ctrlStrip.noClick=!0,this.ctrlStrip.autoFlush=LZR.bind(this,this.ctrlUpdate,this.ctrlStrip));this.constant={}};
LZR.HTML5.Util.Scroll.prototype.className="LZR.HTML5.Util.Scroll";LZR.HTML5.Util.Scroll.prototype.version="0.0.0";
LZR.HTML5.Util.Scroll.prototype.init=function(){this.count=this.srcObj.count;this.padd=this.srcObj.padd;this.len=this.srcObj.len;this.constant.stripPs=LZR.HTML5.Util.getDomPositionForDocument(this.strip);this.constant.btnPs=LZR.HTML5.Util.getDomPositionForDocument(this.btn);if(isNaN(this.len))if(/%$/.test(this.len))switch(this.direction){case 1:this.len=this.constant.stripPs.width*parseFloat(this.len,10)/100;break;case 2:this.len=this.constant.stripPs.height*parseFloat(this.len,10)/100}else this.len=
parseFloat(this.len,10);switch(this.direction){case 1:this.len>this.constant.stripPs.width-this.padd&&(this.len=this.constant.stripPs.width-this.padd);this.btn.style.top=(this.constant.stripPs.height-this.constant.btnPs.height)/2+"px";break;case 2:this.len>this.constant.stripPs.height-this.padd&&(this.len=this.constant.stripPs.height-this.padd),this.btn.style.left=(this.constant.stripPs.width-this.constant.btnPs.width)/2+"px"}this.strip.style.visibility="visible";this.initAutoLen();var a=this.position;
this.position=-1;this.setPosition(a)};LZR.HTML5.Util.Scroll.prototype.initAutoLen=function(){if(0<this.autoLen)switch(r=this.autoLen/this.count,1<=r?(r=1,this.count=0,this.hidTooBig&&(this.strip.style.visibility="hidden")):this.count-=this.autoLen,r*=this.len,r<this.autoMin&&(r=this.autoMin),this.padd+=r/2,this.len-=r,this.direction){case 1:this.btn.style.width=r+"px";this.constant.btnPs.width=r;break;case 2:this.btn.style.height=r+"px",this.constant.btnPs.height=r}};
LZR.HTML5.Util.Scroll.prototype.setPosition=function(a){if(this.position!==a){this.position=a;a/=this.count;1<a?a=1:isNaN(a)&&(a=0);a=a*this.len+this.padd;switch(this.direction){case 1:a-=this.constant.btnPs.width/2;this.btn.style.left=a+"px";break;case 2:a-=this.constant.btnPs.height/2,this.btn.style.top=a+"px"}this.onchange(this.position,this.count)}};
LZR.HTML5.Util.Scroll.prototype.ctrlUpdate=function(a){if(0<this.count){if(!a)if(this.ctrlBtn.state==this.ctrlBtn.STATE.LEFT)a=this.ctrlBtn;else if(this.ctrlStrip.state==this.ctrlStrip.STATE.LEFT)a=this.ctrlStrip;else return;if(a.state==a.STATE.LEFT){var b,c=function(a,b){0>a?a=0:a>b&&(a=b);return a};switch(this.direction){case 1:b=c(a.leftEnd.x-this.constant.stripPs.left-this.padd,this.len);this.btn.style.left=b+this.padd-this.constant.btnPs.width/2+"px";break;case 2:b=c(a.leftEnd.y-this.constant.stripPs.top-
this.padd,this.len),this.btn.style.top=b+this.padd-this.constant.btnPs.height/2+"px"}this.position=b/this.len*this.count;this.onchange(this.position,this.count)}}};LZR.HTML5.Util.Scroll.prototype.ctrlEnable=function(){this.ctrlBtn.state===this.ctrlBtn.STATE.UNABLE&&this.ctrlBtn.enable(!1,!0);this.ctrlStrip.state===this.ctrlStrip.STATE.UNABLE&&this.ctrlStrip.enable(!1,!0)};
LZR.HTML5.Util.Scroll.prototype.ctrlDisable=function(){this.ctrlBtn.state!==this.ctrlBtn.STATE.UNABLE&&this.ctrlBtn.disable();this.ctrlStrip.state!==this.ctrlStrip.STATE.UNABLE&&this.ctrlStrip.disable()};LZR.HTML5.Util.Scroll.prototype.onchange=function(){};
