LZR.HTML5.Util={version:"0.0.1",Layout:{},getEvent:function(a){return window.event||a},getEventTarg:function(a){return window.event.srcElement||a.target},stopDefault:function(a){a=a||window.event;a.preventDefault&&a.preventDefault();a.stopPropagation?a.stopPropagation():(a.returnValue=!1,a.cancelBubble=!0)},stopBubble:function(a){a&&a.stopPropagation?a.stopPropagation():window.event.cancelBubble=!0},getMousePosition:function(a){return a.pageX||a.pageY?{x:a.pageX,y:a.pageY}:{x:window.event.clientX+
document.body.scrollLeft-document.body.clientLeft,y:window.event.clientY+document.body.scrollTop-document.body.clientTop}},getDomPositionForDocument:function(a){var c={left:0,top:0,width:0,height:0};if(a===document)c.left=0,c.top=0,c.width=window.innerWidth,c.height=window.innerHeight;else{var b,d=a.getBoundingClientRect();c.width=d.right-d.left;c.height=d.bottom-d.top;void 0!==window.pageXOffset?(b=a.ownerDocument.documentElement,c.left=d.left-b.clientLeft+window.pageXOffset,c.top=d.top-b.clientTop+
window.pageYOffset):(b=a.ownerDocument.body,c.left=d.left-b.clientLeft+(b.scrollLeft||a.ownerDocument.documentElement.scrollLeft),c.top=d.top-b.clientTop+(b.scrollTop||a.ownerDocument.documentElement.scrollTop))}return c},getParentNode:function(a){return a.parentNode||a.parentElement},clone:function(a){var c;c=a.constructor==Object?new a.constructor:new a.constructor(a.valueOf());for(var b in a)c[b]!=a[b]&&(c[b]="object"==typeof a[b]?a[b].clone?a[b].clone():LZR.HTML5.Util.clone(a[b]):a[b]);return c},
getClassName:function(a){var c=LZR.HTML5.getClassName(a);if("Object"==c){if(a.className)return a.className;var b=a.constructor;if(b==Object)return c;if(a.prototype&&"classname"in a.prototype.constructor&&"string"==typeof a.prototype.constructor.classname)return b.prototype.classname}return c},getClassObj:function(a){return a.__proto__},del:function(a){delete a},bind:function(a,c){var b=Array.prototype.slice.call(arguments,2);return function(){var d,f=[];for(d=0;d<b.length;d++)f.push(b[d]);for(d=0;d<
arguments.length;d++)f.push(arguments[d]);return c.apply(a,f)}},getFileExtension:function(a){if(a){var c=a.lastIndexOf(".")+1;if(0<c)return a.substring(c,a.length).toLowerCase()}return""},addEvent:function(a,c,b,d){a.dispatchEvent?a.addEventListener(c,b,d):a.attachEvent("on"+c,b);return b},removeEvent:function(a,c,b,d){a.dispatchEvent?a.removeEventListener(c,b,d):a.detachEvent("on"+c,b)},addWheel:function(a,c,b){var d="mousewheel";try{document.createEvent("MouseScrollEvents"),d="DOMMouseScroll"}catch(f){}return LZR.HTML5.Util.addEvent(a,
d,function(a){a=LZR.HTML5.Util.getEvent(a);if("wheelDelta"in a){var b=a.wheelDelta;window.opera&&10>opera.version()&&(b=-b);a.delta=Math.round(b)/120}else"detail"in a&&(a.wheelDelta=40*-a.detail,a.delta=a.wheelDelta/120);c(a)},b)},removeWheel:function(a,c,b){var d="mousewheel";try{document.createEvent("MouseScrollEvents"),d="DOMMouseScroll"}catch(f){}LZR.HTML5.Util.removeEvent(a,d,c,b)},formatFloat:function(a,c){var b=Math.pow(10,c);return parseInt(a*b,10)/b},toAbsURL:function(){var a=function(a){var b=
document.createElement("a");b.href=a;return b.href};return""===a("")?function(a){var b=document.createElement("div");b.innerHTML='<a href="'+a.replace(/"/g,"%22")+'"/>';return b.firstChild.href}:a}(),filter:function(a,c,b,d){d||(d={});var f=b?function(a){return LZR.HTML5.Util.clone(a)}:function(a){return a},e;for(e in c)if(null===c[e])d[e]=f(a[e]);else switch(typeof c[e]){case "string":d[c[e]]=f(a[e]);break;case "number":d[e]=arguments[c[e]+4];break;case "object":var g=c[e].type,h=c[e].name,h=h?h:
e,g=g?g:"obj";switch(g){case "ary":d[h]=[];var g=0,i;for(i in a[e])d[h][g]=c[e].tmp?LZR.HTML5.Util.filter(a[e][i],c[e].tmp,b,{},g+1):f(a[e][i]),g++;break;case "obj":d[h]=LZR.HTML5.Util.filter(a[e],c[e].tmp,b);break;default:d[h]=c[e].tmp}break;default:d[e]=f(a[e])}return d},query:function(a,c){var b;switch(LZR.HTML5.Util.getClassName(a)){case "Array":case "NodeList":b=[];for(var d=0;d<a.length;d++)LZR.HTML5.Util.and(a[d],c)&&b.push(a[d]);break;default:for(d in b={},a)LZR.HTML5.Util.and(a[d],c)&&(b[d]=
a[d])}return b},and:function(a,c){for(var b in c)switch(b.substring(0,6)){case "LZRand":if(!LZR.HTML5.Util.and(a,c[b]))return!1;break;case "LZRorr":if(!LZR.HTML5.Util.orr(a,c[b]))return!1;break;case "LZRnot":break;case "LZRhas":break;default:if(a[b]!=c[b])return!1}return!0},orr:function(a,c){for(var b in c)switch(b.substring(0,6)){case "LZRand":if(LZR.HTML5.Util.and(a,c[b]))return!0;break;case "LZRorr":if(LZR.HTML5.Util.orr(a,c[b]))return!0;break;case "LZRnot":break;case "LZRhas":break;default:if(a[b]==
c[b])return!0}return!1},appendTbody:function(a,c,b,d){var f,e,g;if(b)for(f=a.children.length-1;0<=f;f--)if(e=a.children[f],c.title)a.removeChild(e);else for(b=0;b<e.children.length;b++)if("TD"==e.children[b].tagName){a.removeChild(e);break}if(c.title){e=document.createElement("tr");for(f in c.title)g=document.createElement("th"),g.innerHTML=c.title[f],d&&(g.name=f),e.appendChild(g);a.appendChild(e)}for(b=0;b<c.data.length;b++){e=document.createElement("tr");for(f in c.data[b])g=document.createElement("td"),
g.innerHTML=c.data[b][f],d&&(g.name=f),e.appendChild(g);a.appendChild(e)}},getVals:function(a,c,b){var a=LZR.HTML5.Util.query(a,c),c=0,d;for(d in a){var f=parseInt(a[d][b],10);isNaN(f)||(c+=f)}return c},getRequest:function(){var a=location.search,c={};if(-1!=a.indexOf("?"))for(var a=a.substr(1).split("&"),b=0;b<a.length;b++){var d=a[b].split("=");c[d[0]]=unescape(d[1])}return c},format:function(a,c,b){var a=a+"",d=a.length;if(c>d){d=c-d;for(c=0;c<d;c++)a=b+a}return a},mateWidth:function(a){a.scrollWidth!==
a.width?(a.width=a.scrollWidth,a.height=a.scrollHeight):a.scrollHeight!==a.height&&(a.height=a.scrollHeight)},backfill:function(a){for(var c in a){var b=document.getElementsByName(c);if(1==b.length)switch(b[0].targName){case "input":b[0].value=a[c];break;case "textarea":b[0].innerHTML=a[c]}}}};
