LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/Canvas/LayerManager.js",LZR.HTML5.jsPath+"HTML5/Canvas/Thumbnail.js",LZR.HTML5.jsPath+"HTML5/Bp/AirqMg/RegImg.js",LZR.HTML5.jsPath+"HTML5/util/Scroll.js",LZR.HTML5.jsPath+"HTML5/Canvas/ImgLoader.js"]);
LZR.HTML5.Bp.AirqMg.ImgLib=function(a){this.title=a.title;LZR.HTML5.Util.mateWidth(a.map);a.map.style.cursor="crosshair";this.map=new LZR.HTML5.Canvas.LayerManager(a.map);this.map.ctrl.leftCursor="move";LZR.HTML5.Util.mateWidth(a.tbn);this.tbn=new LZR.HTML5.Canvas.Thumbnail(a.tbn);this.tbn.direction=2;this.tbn.width=156;this.tbn.height=120;this.tbn.paddingU=40;this.tbn.offsetU=10;this.tbn.offsetV=10;this.tbn.buff=0;this.tbn.wheelScale=1;this.tbn.wheelStyle=2;this.tbn.ctx.fillStyle="#777";this.tbn.draw=
LZR.bind(this,function(a,e,c,d,g,f){a.ctx.fillText(a.imgs[e].tim,c+this.tbnFont[0].left,d+f+this.tbnFont[0].bottom)});this.tbn.onchange=LZR.HTML5.Util.bind(this,function(a){this.map.layers[0].obj=this.tbn.imgs[a].getLayers()[0].obj;this.changeTitle()});this.tbns=new LZR.HTML5.Canvas.ImgLoader(LZR.bind(this,this.onTbns));this.ctrlEnable=1;this.path="";this.playSpeed=1;this.playState=0;this.playFrame=1;this.scrollObj=a.scrollObj;this.tbnFont=[{left:12,bottom:25,font:"20px Verdana"}];this.wsInfo={url:"ws://192.168.1.211:8989",
typ:"picContent",pre:"data:image/jpeg;base64,",fld:"Byte64"};this.mapLimitCenter=!1;LZR.HTML5.Util.Event.addEvent(window,"resize",LZR.bind(this,this.resize),!1)};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.className="LZR.HTML5.Bp.AirqMg.ImgLib";LZR.HTML5.Bp.AirqMg.ImgLib.prototype.version="0.0.2";
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.init=function(){this.tbn.ctx.font=this.tbnFont[0].font;this.pic=document.createElement("img");this.pic.onload=LZR.bind(this,function(){this.map.addLayer(new LZR.HTML5.Canvas.Layer(this.pic),"\u56fe\u7247");this.map.init();this.tbn.init();this.initMap();this.initTbn();this.ctrlStart();this.loadTbns()});this.pic.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABGdBTUEAALGPC/xhBQAAAA5JREFUKFNjYBgFgzMEAAGaAAFUMoc2AAAAAElFTkSuQmCC"};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.ctrlStart=function(){this.map.ctrlEnable();this.tbn.ctrlEnable();this.scroll.ctrlEnable();this.ctrl(this.playSpeed,!0)};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.ctrlStop=function(){this.ctrlEnable=0;this.map.ctrlDisable();this.tbn.ctrlDisable();this.scroll.ctrlDisable()};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.ctrl=function(a,b){switch(this.ctrlEnable){case 0:this.ctrlEnable=b?1:2;break;case 1:this.map.ctrlUpdate();this.tbn.ctrlUpdate();this.map.flush();this.tbn.flush();a=this.play(a);this.fulshScroll();requestAnimationFrame(LZR.HTML5.Util.bind(this,this.ctrl,a));break;case 2:b&&(this.ctrlEnable=1)}};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.loadTbns=function(){var a=this.imginfo,b={type:this.wsInfo.typ,picType:[a],sort:0};switch(this.typ){case "yu":b[a]={times:this.date+this.tim,periodStart:0,periodEnd:240};break;case "child":b[a]={timesRange:[this.liveStartDate,this.liveEndDate]}}this.tbns.addByWebSocket(this.wsInfo,b)};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.initMap=function(a){a||(a=this.pic,this.map.layers[0].obj=this.pic);this.map.s.top=0;this.map.s.left=0;this.map.s.w=a.width;this.map.s.reHeight();this.map.resetMax(0,0,a.width,a.height);this.mapLimitCenter&&(this.map.resetMax(0,0,a.width,a.height),this.map.max.rrByParent(this.map.s),this.map.s.w*=this.map.max.baseW/this.map.max.w,this.map.s.reHeight(),this.map.max.w=this.map.max.baseW,this.map.max.reHeight(),this.map.s.alineInParent("center",this.map.max))};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.initTbn=function(a){a||(a=0);this.tbn.index=0;this.tbn.imgs=[];this.tbn.count=a;this.tbn.calculateMax();this.createScroll()};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.onTbns=function(a,b,e){var c=new LZR.HTML5.Bp.AirqMg.RegImg;c.tim="";for(var d=0;d<e.picTime.length;d++)switch(c.tim+=e.picTime[d],d){case 3:case 5:c.tim+="-";break;case 7:c.tim+=" "}c.tim+="\u65f6";c.layers.push(new LZR.HTML5.Canvas.Layer({name:e.name,obj:b}));this.tbn.imgs.push(c);this.tbn.count++;this.tbn.calculateMax();this.createScroll();0===a&&(this.initMap(b),this.tbn.onchange(0))};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.clear=function(){this.tbns.closeWebSocket();this.initMap();this.initTbn();this.playState=0;this.playSpeed=1;this.title.innerHTML=""};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.changeTitle=function(){this.title.innerHTML=this.tbn.imgs[this.tbn.index].tim+"_"+this.memo};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.play=function(a){if(1==this.playState)if(0<a)a--;else{var a=this.playSpeed,b=this.playFrame,b=b+this.tbn.index;b>=this.tbn.count&&(b=0);this.tbn.select(b)}return a};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.changeAnimation=function(){if(-1==this.playState)return 0;1==this.playState?(this.playState=0,this.tbn.ctrlEnable(),this.scroll.ctrlEnable()):(this.tbn.ctrlDisable(),this.scroll.ctrlDisable(),this.playState=1);return this.playState};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.changeHeadTail=function(a){a?this.tbn.select(this.tbn.count):this.tbn.select(0);return this.playState};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.changePage=function(a){this.tbn.select(this.tbn.index+a*this.playFrame)};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.setSpeed=function(a){this.playSpeed+=a;30<this.playSpeed?this.playSpeed=30:0>this.playSpeed&&(this.playSpeed=0)};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.createScroll=function(a){this.scroll?(this.scroll.srcObj.count=this.tbn.max+this.tbn.canvas.height,this.scroll.position=a?a:0,this.scroll.autoLen=this.tbn.canvas.height):(this.scrollObj.count=this.tbn.max+this.tbn.canvas.height,this.scrollObj.position=0,this.scrollObj.autoLen=this.tbn.canvas.height,this.scrollObj.direction=2,this.scrollObj.autoMin=20,this.scrollObj.hidTooBig=!0,this.scrollObj.padd=0,this.scrollObj.len="100%",this.scroll=new LZR.HTML5.Util.Scroll(this.scrollObj),
this.scroll.onchange=LZR.bind(this,function(a){this.tbn.position=a}));this.scroll.init()};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.fulshScroll=function(){this.tbn.position!==this.scroll.position&&this.scroll.setPosition(this.tbn.position)};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.resize=function(){this.map.resize();this.tbn.resize();this.createScroll(this.scroll.position)};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.setInfo=function(a,b,e,c,d){this.imginfo=a;this.memo=b;this.typ=e;this.tim=c;d&&(this.clear(),this.loadTbns())};
LZR.HTML5.Bp.AirqMg.ImgLib.prototype.setDate=function(a,b){this.date=a;b&&(this.clear(),this.loadTbns())};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.setLiveStartDate=function(a,b){this.liveStartDate=a;b&&(this.clear(),this.loadTbns())};LZR.HTML5.Bp.AirqMg.ImgLib.prototype.setLiveEndDate=function(a,b){this.liveEndDate=a;b&&(this.clear(),this.loadTbns())};
