LZR.HTML5.loadJs([LZR.HTML5.jsPath+"util/Date.js",LZR.HTML5.jsPath+"HTML5/Canvas/LayerMgrEys.js",LZR.HTML5.jsPath+"HTML5/Canvas/Thumbnail.js",LZR.HTML5.jsPath+"HTML5/Bp/AirqMg/RegImg.js",LZR.HTML5.jsPath+"HTML5/Bp/AirqMg/RegStatRule.js",LZR.HTML5.jsPath+"HTML5/util/Scroll.js",LZR.HTML5.jsPath+"HTML5/Canvas/ImgLoader.js"]);
LZR.HTML5.Bp.AirqMg.RegStat=function(a){this.condition=a.condition?a.condition:{};this.title=a.title;LZR.HTML5.Util.mateWidth(a.map);a.map.style.cursor="crosshair";this.map=new LZR.HTML5.Canvas.LayerManager(a.map);this.map.max.reset({top:1,left:1,width:1438,height:1118});this.map.s.top=1;this.map.s.left=1;this.map.s.w=this.map.max.w;this.map.s.reHeight();this.map.min.reset({width:100,height:100});this.map.offset={left:40,top:1,right:1,bottom:25};this.map.ctrl.leftCursor="move";this.map.autoFlush=
LZR.HTML5.Util.bind(this,this.mapAutoFlush);LZR.HTML5.Util.mateWidth(a.eys);a.eys.style.cursor="crosshair";this.eys=new LZR.HTML5.Canvas.LayerMgrEys({canvas:a.eys,layerMgr:this.map});LZR.HTML5.Util.mateWidth(a.tbn);this.tbn=new LZR.HTML5.Canvas.Thumbnail(a.tbn);this.tbn.direction=2;this.tbn.width=156;this.tbn.height=120;this.tbn.paddingU=40;this.tbn.offsetU=10;this.tbn.offsetV=10;this.tbn.buff=0;this.tbn.ctx.fillStyle="black";this.tbn.onchange=LZR.HTML5.Util.bind(this,function(a){this.map.layers=
this.tbn.imgs[a].getLayers();this.changeTitle()});this.maps=new LZR.HTML5.Canvas.ImgLoader(LZR.HTML5.Util.bind(this,this.onMaps));this.playSpeed=this.ctrlEnable=1;this.playState=0;this.playFrame=1;this.compass={};this.legend={};this.ruler=null;this.scrollObj=a.scrollObj;this.boderColor=null;this.path="";this.tbnFont=[{left:25,bottom:20,font:"17px Verdana"},{left:5,bottom:20,font:"17px Verdana"}];this.dayNum=7;this.hourStep=1;this.rulerArea={latt:55,latb:8,lonl:69,lonr:140,dlon:9,dlat:8};this.periodStart=
4;this.layersLoader=[];this.layersLoader[0]=new LZR.HTML5.Canvas.ImgLoader(LZR.bind(this,this.onLayersLoad,0));this.layersLoader[0].finished=LZR.bind(this,function(){this.tbnFinished()});this.createLayersLoader();this.wsInfo={url:"ws://192.168.1.211:8989",typ:"picURL",pre:"http://192.168.1.101/imgServer/figure/figure/",fld:"URL"};LZR.HTML5.Util.Event.addEvent(window,"resize",LZR.bind(this,this.resize),!1)};LZR.HTML5.Bp.AirqMg.RegStat.prototype.className="LZR.HTML5.Bp.AirqMg.RegStat";
LZR.HTML5.Bp.AirqMg.RegStat.prototype.version="0.0.7";LZR.HTML5.Bp.AirqMg.RegStat.prototype.init=function(){this.initTbn();this.map.init();this.tbn.init();this.eys.init();this.loadEys();this.createRuler();this.createScroll();this.loadMaps()};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.initTbn=function(){1==this.condition.ttyp?(this.tbn.index=(new Date).getHours(),this.tbn.index=this.tbn.index>this.condition.tim?Math.floor((this.tbn.index-this.condition.tim)/this.hourStep)+1:0,this.tbn.count=Math.ceil((24-this.condition.tim)/this.hourStep),this.tbn.count+=Math.floor(24*(this.dayNum-1)/this.hourStep),this.tbn.ctx.font=this.tbnFont[1].font,this.tbn.wheelScale=3,this.tbn.wheelStyle=2,this.tbn.draw=LZR.bind(this,function(a,c,b,d,g,e){a.ctx.fillText(a.imgs[c].tim,
b+this.tbnFont[1].left,d+e+this.tbnFont[1].bottom)})):(this.tbn.index=0,this.tbn.count=this.dayNum,this.tbn.ctx.font=this.tbnFont[0].font,this.tbn.wheelScale=1,this.tbn.wheelStyle=2,this.tbn.draw=LZR.bind(this,function(a,c,b,d,g,e){a.ctx.fillText(a.imgs[c].tim,b+this.tbnFont[0].left,d+e+this.tbnFont[0].bottom)}))};LZR.HTML5.Bp.AirqMg.RegStat.prototype.ctrlStart=function(){this.map.ctrlEnable();this.tbn.ctrlEnable();this.eys.ctrlEnable();this.scroll.ctrlEnable();this.ctrl(this.playSpeed,!0)};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.loadEys=function(a){this.eys.layers=[];a||(a=this.path);a+="D"+this.condition.area+".png";this.maps.add(a,0,LZR.HTML5.Util.bind(this,function(a,b){this.eys.layers.push(new LZR.HTML5.Canvas.Layer({name:"\u5730\u56fe",obj:b}))}))};LZR.HTML5.Bp.AirqMg.RegStat.prototype.ctrlStop=function(){this.ctrlEnable=0;this.map.ctrlDisable();this.tbn.ctrlDisable();this.eys.ctrlDisable();this.scroll.ctrlDisable()};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.ctrl=function(a,c){switch(this.ctrlEnable){case 0:this.ctrlEnable=c?1:2;break;case 1:this.pen&&this.pen.ctrlUpdate();this.map.ctrlUpdate();this.tbn.ctrlUpdate();this.eys.ctrlUpdate();this.map.flush();this.tbn.flush();this.eys.flush();a=this.play(a);this.fulshScroll();requestAnimationFrame(LZR.HTML5.Util.bind(this,this.ctrl,a));break;case 2:c&&(this.ctrlEnable=1)}};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.loadMaps=function(a){a||(a=this.path);a+="D"+this.condition.area+".png";this.maps.add(a,this.condition.area)};LZR.HTML5.Bp.AirqMg.RegStat.prototype.onMaps=function(a,c){this.map.layers=[];this.tbn.imgs=[];this.fillLayers(c);this.ctrlStart();this.loadLayers(0);this.mapFinished()};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.createLayersLoader=function(){this.layersNum=2+this.condition.layersInfo.length;for(var a=function(a){this.otherFinished(a)},c=2;c<this.layersNum;c++){var b=new LZR.HTML5.Canvas.ImgLoader(LZR.bind(this,this.onLayersLoad,c));b.finished=LZR.bind(this,a,c);this.layersLoader[c]=b}};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.fillLayers=function(a){var c,b,d;for(c=0;c<this.tbn.count;c++){var g=this.createImg(c,this.condition.date);for(b=0;b<this.layersNum;b++)d=new LZR.HTML5.Canvas.Layer,d.visible=!1,g.layers.push(d);g.layers[1].obj=a;g.layers[1].visible=!0;g.layers[0].visible=!0;this.tbn.imgs.push(g)}c=this.tbn.index;this.map.layers=this.tbn.imgs[c].layers;this.tbn.aline(c,!0);this.changeTitle()};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.createImg=function(a,c){var b=new LZR.HTML5.Bp.AirqMg.RegImg;1==this.condition.ttyp?(c+=36E5*(a*this.hourStep+this.condition.tim),c=new Date(c),b.tim=c.getFullYear(),b.tim+="-",b.tim+=LZR.HTML5.Util.format(c.getMonth()+1,2,"0"),b.tim+="-",b.tim+=LZR.HTML5.Util.format(c.getDate(),2,"0"),b.tim+=" ",b.tim+=LZR.HTML5.Util.format(c.getHours(),2,"0"),b.tim+="\u65f6"):(c=new Date(c+864E5*a),b.tim=c.getFullYear(),b.tim+="-",b.tim+=LZR.HTML5.Util.format(c.getMonth()+1,
2,"0"),b.tim+="-",b.tim+=LZR.HTML5.Util.format(c.getDate(),2,"0"));return b};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.loadLayers=function(a){var c,b,d={type:this.wsInfo.typ,sort:0};this.layersLoader[a].closeWebSocket();switch(a){case 0:c=this.condition.fom[this.condition.ttyp];b=this.condition.mod;this.createTbnQry(d,c,b);break;default:c=this.condition.layersInfo[a-2].typ[this.condition.ttyp],b=this.condition.layersInfo[a-2].mod,this.createWeatherQry(d,c,b)}this.layersLoader[a].addByWebSocket(this.wsInfo,d)};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.createTbnQry=function(a,c,b){return this.createWeatherQry(a,c,b)};LZR.HTML5.Bp.AirqMg.RegStat.prototype.createWeatherQry=function(a,c,b){a.picType=[c];a[c]={modelType:[b],domain:["d"+LZR.HTML5.Util.format(this.condition.area,2,"0")],times:this.condition._date+this.condition._tim,periodStart:this.periodStart,periodEnd:24*this.dayNum+this.periodStart};return a};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.onLayersLoad=function(a,c,b){if(c=this.tbn.imgs[c])c.layers[a].obj=b};LZR.HTML5.Bp.AirqMg.RegStat.prototype.clear=function(){this.ctrlStop();this.map.layers=[];this.tbn.imgs=[];this.ruler=null;this.playSpeed=1};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.changeTitle=function(){this.title.innerHTML=this.tbn.imgs[this.tbn.index].tim+" "+this.condition.mod+"\u6a21\u5f0f"+this.condition.fomName+this.condition.areaName+"\u533a\u57df\u5f62\u52bf <sub>\uff08\u4ea7\u54c1\u65f6\u95f4\uff1a"+this.condition.dateName+" "+this.condition.timName+"\uff09</sub >"};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.play=function(a){if(1==this.playState)if(0<a)a--;else{var a=this.playSpeed,c=this.playFrame,c=c+this.tbn.index;c>=this.tbn.count&&(c=0);this.tbn.select(c)}return a};LZR.HTML5.Bp.AirqMg.RegStat.prototype.changeAnimation=function(){if(-1==this.playState)return 0;1==this.playState?(this.playState=0,this.tbn.ctrlEnable(),this.scroll.ctrlEnable()):(this.tbn.ctrlDisable(),this.scroll.ctrlDisable(),this.playState=1);return this.playState};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setFrame=function(a){this.playFrame=a};LZR.HTML5.Bp.AirqMg.RegStat.prototype.changeHeadTail=function(a){a?this.tbn.select(this.tbn.count):this.tbn.select(0);return this.playState};LZR.HTML5.Bp.AirqMg.RegStat.prototype.changePage=function(a){this.tbn.select(this.tbn.index+a*this.playFrame)};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setSpeed=function(a){this.playSpeed+=a;30<this.playSpeed?this.playSpeed=30:0>this.playSpeed&&(this.playSpeed=0)};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.clrLayers=function(a){for(var c=0;c<this.tbn.count;c++){var b=this.tbn.imgs[c].layers;if(isNaN(a)){b[0].obj=void 0;for(var d=2;d<this.layersNum;d++)b[d].obj=void 0}else b[a].obj=void 0}};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setMapMax=function(a,c,b,d){this.map.max.reset({top:a,left:c,width:b,height:d});this.map.s.top=a;this.map.s.left=c;this.map.s.w=b;this.map.s.reHeight();this.eys.lmEdge.reset({top:a,left:c,width:b,height:d})};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setMod=function(a,c,b){this.condition.mod=a;c&&(this.clear(),b&&this.setDayNum(b),this.init())};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setFom=function(a,c,b){this.condition.fomName=a;this.condition.fom=c;b&&(this.changeTitle(),this.clrLayers(0),this.loadLayers(0))};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setDate=function(a,c){this.condition.dateName=a;this.condition._date=a.replace(/-/g,"");this.condition.date=LZR.Util.Date.getDate(a).valueOf()+864E5;c&&(this.clear(),this.init())};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setTim=function(a,c,b){this.condition.timName=a;this.condition._tim=c;this.condition.tim=0;b&&(this.changeTitle(),this.clrLayers(),this.loadLayers(0))};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setTtyp=function(a,c,b){this.condition.ttypName=a;this.condition.ttyp=c;b&&(this.clear(),this.init())};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setArea=function(a,c,b,d,g){this.condition.areaName=a;this.condition.area=c;b&&(this.clear(),this.setDayNum(d),this.setRulerArea(g),this.init())};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setDayNum=function(a){a&&(this.dayNum=a)};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setRulerArea=function(a){a&&(isNaN(a.latt)||(this.rulerArea.latt=a.latt),isNaN(a.latb)||(this.rulerArea.latb=a.latb),isNaN(a.lonl)||(this.rulerArea.lonl=a.lonl),isNaN(a.lonr)||(this.rulerArea.lonr=a.lonr),isNaN(a.dlon)||(this.rulerArea.dlon=a.dlon),isNaN(a.dlat)||(this.rulerArea.dlat=a.dlat))};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setLayerVisble=function(a,c){for(var b=0;b<this.tbn.count;b++)this.tbn.imgs[b].layers[a].visible=c};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setLayerAlpha=function(a,c){isNaN(c)||(0>c?c=0:1<c&&(c=1));for(var b=0;b<this.tbn.count;b++)this.tbn.imgs[b].layers[a].alpha=c};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.loadCompass=function(a){this.maps.add(a,101,LZR.HTML5.Util.bind(this,function(a,b){this.compass.resize=LZR.bind(this,function(){this.compass.h=0.15*this.map.canvas.height;this.compass.h>this.compass.baseH&&(this.compass.h=this.compass.baseH);this.compass.w=this.compass.h*this.compass.scale});this.compass.img=b;this.compass.visible=!0;this.compass.baseH=b.height;this.compass.scale=b.width/b.height;this.compass.resize()}))};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setCompassVisble=function(a){this.compass.img&&(this.compass.visible=a)};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.loadLegend=function(a){this.legend.resize=LZR.bind(this,function(){1<this.legend.scale?(this.legend.w=0.4*this.map.canvas.width,this.legend.w>this.legend.baseW&&(this.legend.w=this.legend.baseW),this.legend.h=this.legend.w/this.legend.scale):(this.legend.h=0.4*this.map.canvas.height,this.legend.h>this.legend.baseH&&(this.legend.h=this.legend.baseH),this.legend.w=this.legend.h*this.legend.scale)});this.legend.visible=!0;this.legend.alpha=1;this.maps.add(a,102,
LZR.HTML5.Util.bind(this,function(a,b){this.legend.img=b;this.legend.OverImg||(this.legend.OverImg=b);this.legend.baseW=b.width;this.legend.baseH=b.height;this.legend.scale=b.width/b.height;this.legend.resize()}))};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setLegendImg=function(a){this.maps.add(a,103,LZR.HTML5.Util.bind(this,function(a,b){this.legend.img=b;this.legend.baseW=b.width;this.legend.baseH=b.height;this.legend.scale=b.width/b.height;this.legend.resize()}))};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.setLegendOverImg=function(a){this.maps.add(a,104,LZR.HTML5.Util.bind(this,function(a,b){this.legend.OverImg=b;this.legend.baseW=b.width;this.legend.baseH=b.height;this.legend.scale=b.width/b.height;this.legend.resize()}))};LZR.HTML5.Bp.AirqMg.RegStat.prototype.setLegendVisble=function(a){this.legend.img&&(this.legend.visible=a)};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.createRuler=function(){this.ruler=new LZR.HTML5.Bp.AirqMg.RegStatRule({rs:this,latt:this.rulerArea.latt,latb:this.rulerArea.latb,lonl:this.rulerArea.lonl,lonr:this.rulerArea.lonr,min:50,max:70,dlon:this.rulerArea.dlon,dlat:this.rulerArea.dlat})};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.createScroll=function(a){this.scroll?(this.scroll.srcObj.count=this.tbn.max+this.tbn.canvas.height,this.scroll.position=a?a:0,this.scroll.autoLen=this.tbn.canvas.height):(this.scrollObj.count=this.tbn.max+this.tbn.canvas.height,this.scrollObj.position=0,this.scrollObj.autoLen=this.tbn.canvas.height,this.scrollObj.direction=2,this.scrollObj.autoMin=20,this.scrollObj.hidTooBig=!0,this.scrollObj.padd=0,this.scrollObj.len="100%",this.scroll=new LZR.HTML5.Util.Scroll(this.scrollObj),
this.scroll.onchange=LZR.bind(this,function(a){this.tbn.position=a}));this.scroll.init()};LZR.HTML5.Bp.AirqMg.RegStat.prototype.fulshScroll=function(){this.tbn.position!==this.scroll.position&&this.scroll.setPosition(this.tbn.position)};LZR.HTML5.Bp.AirqMg.RegStat.prototype.resize=function(){this.map.resize();this.tbn.resize();this.eys.resize();this.loadEys();this.createScroll(this.scroll.position);this.legend.resize();this.compass.resize()};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.mapAutoFlush=function(a,c,b,d,g){var e,f;a.globalAlpha=1;this.boderColor&&(a.lineWidth="2",a.fillStyle=this.boderColor,a.strokeStyle=this.boderColor,a.strokeRect(c,0,d,g+b),a.fillRect(c,0,d,b));this.compass.visible&&(e=this.compass.w,a.drawImage(this.compass.img,c+d-e-5,b+5,e,this.compass.h));if(this.legend.visible&&this.legend.img){e=this.legend.w;f=this.legend.h;var k=this.map.constant.d,j=c+d-e-15,i=b+g-f-15,h=this.map.ctrl.currentPage.x-k.left-j,k=this.map.ctrl.currentPage.y-
k.top-i;a.globalAlpha=this.legend.alpha;0<h&&h<e&&0<k&&k<f?a.drawImage(this.legend.OverImg,j,i,e,f):a.drawImage(this.legend.img,j,i,e,f);a.globalAlpha=1}j=this.ruler.update();a.lineWidth="2";a.strokeStyle="black";a.fillStyle="black";a.font="10px Verdana";e=c+15;f=b+g-15;a.beginPath();a.moveTo(e,f-10);a.lineTo(e,f);e+=j.w;a.lineTo(e,f);a.lineTo(e,f-10);a.stroke();h=j.d;a.fillText(1E3<h?h/1E3+"\u516c\u91cc":h+"\u7c73",e+10,f);this.boderColor&&(a.strokeStyle=this.boderColor);h=this.ruler.getLatRod();
j=g/(h.length-1);for(i=0;i<h.length;i++)f=j*i+b,a.beginPath(),a.moveTo(c-10,f),a.lineTo(c,f),a.stroke(),a.fillText(h[i].toFixed(1),c-40,f+10);h=this.ruler.getLonRod();j=d/(h.length-1);f=b+g;for(i=0;i<h.length;i++)e=j*i+c,a.beginPath(),a.moveTo(e,f+10),a.lineTo(e,f),a.stroke(),a.fillText(h[i].toFixed(1),e-35,f+22)};LZR.HTML5.Bp.AirqMg.RegStat.prototype.isBusyInLayersLoader=function(a){return this.layersLoader[a]?this.layersLoader[a].isBusy:!1};LZR.HTML5.Bp.AirqMg.RegStat.prototype.mapFinished=function(){};
LZR.HTML5.Bp.AirqMg.RegStat.prototype.tbnFinished=function(){};LZR.HTML5.Bp.AirqMg.RegStat.prototype.otherFinished=function(){};
