LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/util/TimeAxisBurst.js"]);LZR.HTML5.loadCss([LZR.HTML5.jsPath+"css/LHBU_BpTimeAxis.css"]);
LZR.HTML5.Bp.Util.BpTimeAxis=function(a){this.div=a.div?a.div:document.createElement("div");this.playBtn=new LZR.HTML5.Util.Select({data:{title:"\u64ad\u653e\u52a8\u753b",checked:!1},type:0,defaultClass:"LHU_BpTimeAxis_play",downClass:"LHU_BpTimeAxis_pause"});this.div.appendChild(this.playBtn.div);a.hidPlay&&(this.playBtn.div.style.display="none");this.ta=new LZR.HTML5.Util.BaseTimeAxis({currentTitleClass:"LHU_BpTimeAxis_ct",mouseTitleClass:"LHU_BpTimeAxis_mt",backStripClass:"LHU_BpTimeAxis_bs",coverStripClass:"LHU_BpTimeAxis_cs",
scrollBtnClass:"LHU_BpTimeAxis_sb",startTime:a.startTime,timeLong:a.timeLong,timeStep:a.timeStep,style:a.style,allShow:a.allShow,noDrop:a.noDrop,titleOver:-18,hidTitle:a.hidTitle,hoverTime:a.hoverTime,playStep:a.playStep,playSpeed:a.playSpeed,playMod:a.playMod,div:this.div});this.tb=this.createTb(a.count,a.data);LZR.HTML5.Util.Event.addEvent(window,"resize",LZR.bind(this,function(){this.init()}),!1);this.playBtn.onDown=LZR.bind(this,function(a){a.checked?this.play():(this.stop(),this.autoStop())});
this.ta.autoStop=LZR.bind(this,function(){this.playBtn.setChecked(!1);this.autoStop()});this.ta.onchange=LZR.bind(this,function(a,c){return this.onchange(a,c)});this.ta.getCurrentTitleContent=LZR.bind(this,function(a){return this.getCurrentTitleContent(a)});this.ta.getMouseTitleContent=LZR.bind(this,function(a){return this.getMouseTitleContent(a)})};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.className="LZR.HTML5.Bp.Util.BpTimeAxis";LZR.HTML5.Bp.Util.BpTimeAxis.prototype.version="0.0.3";
LZR.HTML5.Bp.Util.BpTimeAxis.prototype.init=function(a){this.ta.init(a);this.tb.init()};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.play=function(){!1!==this.beforePlay()&&this.ta.play()};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.stop=function(){this.ta.pause();this.playBtn.setChecked(!1)};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.next=function(){this.ta.next()};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.back=function(){this.ta.back()};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.setPosition=function(a){this.ta.setPosition(a)};
LZR.HTML5.Bp.Util.BpTimeAxis.prototype.createTb=function(a,b){return new LZR.HTML5.Util.TimeAxisBurst({bta:this.ta,count:a,data:b,outClass:"LHU_BpTimeAxis_tb",defaultClass:"LHU_BpTimeAxis_tbf",overClass:"LHU_BpTimeAxis_tbo",downClass:"LHU_BpTimeAxis_tbd",offsetW:1,noBorder:!0})};
LZR.HTML5.Bp.Util.BpTimeAxis.prototype.setter=function(a,b){var c,d;switch(a){case "count":c=b;case "data":void 0===c&&(d=b);this.ta.cover.removeChild(this.tb.div);this.tb=this.createTb(c,d);this.tb.init();break;case "startTime":this.ta.startTime=this.ta.calcStartTime(b);this.ta.scroll.position=0;this.ta.init();this.stop();this.ta.cover.removeChild(this.tb.div);this.tb=this.tb.count?this.createTb(this.tb.count):this.createTb(void 0,this.tb.data);this.tb.init();break;case "timeLong":this.ta.setTimeLong(b);
this.stop();break;case "timeStep":this.ta.timeStep=1E3*b;this.stop();break;case "playStep":this.ta.playStep=b;break;case "playSpeed":this.ta.setPlaySpeed(b);break;case "playMod":this.ta.playMod=b;break;case "allShow":this.ta.setAllShow(b);break;case "hidPlay":this.playBtn.div.style.display=b?"none":"";this.stop();break;case "style":this.ta.style=b;this.ta.init();break;case "noDrop":this.ta.noDrop=b;break;case "hidTitle":this.ta.setHidTitle(b)}};
LZR.HTML5.Bp.Util.BpTimeAxis.prototype.getCurrentTime=function(){return this.ta.getCurrentTime()};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.flushCurrentTime=function(){this.ta.currentTitle.innerHTML=this.getCurrentTitleContent(this.getCurrentTime())};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.getCurrentTitleContent=function(a){return LZR.HTML5.Util.format(a.getHours(),2,"0")+":"+LZR.HTML5.Util.format(a.getMinutes(),2,"0")};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.getMouseTitleContent=function(a){return this.getCurrentTitleContent(a)};
LZR.HTML5.Bp.Util.BpTimeAxis.prototype.onchange=function(){};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.beforePlay=function(){};LZR.HTML5.Bp.Util.BpTimeAxis.prototype.autoStop=function(){};
