LZR.HTML5.loadJs([LZR.HTML5.jsPath+"util/Date.js",LZR.HTML5.jsPath+"HTML5/Bp/AirqMg/RegStat2.js",LZR.HTML5.jsPath+"HTML5/Bp/Util/CatchImgByWebsocket/Forecast.js"]);LZR.HTML5.Bp.AirqMg.RegStat2.Query=function(a){this.index=-1;this.foc=new LZR.HTML5.Bp.Util.CatchImgByWebsocket.Forecast;this.data=null;this.layers=[];this.backImg="back.png";this.backJson="back.json";this.callback();a&&LZR.setObj(this,a)};LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.className="LZR.HTML5.Bp.AirqMg.RegStat2.Query";
LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.version="0.0.2";LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.setQry=function(a){a&&LZR.setObj(this.foc,a)};LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.open=function(){this.index=0;this.qry()};LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.close=function(){this.foc.close();this.index=-1};
LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.qry=function(){var a=this.layers[this.index];if(a)switch(a.className){case "LZR.HTML5.Bp.AirqMg.RegStat2.OlLayer":case "LZR.HTML5.Bp.AirqMg.RegStat2.OlGeoJsonLayer":this.foc.num=a.num.val;this.foc.open();break;case "LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer":this.handleClose(this.creWindSQL(a))}else this.index=-1};
LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.handleTime=function(a){if(this.data.cur.timeStep)switch(this.data.cur.timeStep.id){case "hour":return this.handleTimeToHour(a);case "day":return this.handleTimeToDay(a)}return a};LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.handleTimeToHour=function(a){for(var b="",c=0;c<a.length;c++)switch(b+=a[c],c){case 3:case 5:b+="-";break;case 7:b+=" "}return b+"\u65f6"};
LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.handleTimeToWindHour=function(a){a=this.handleTimeToDay(a);a=LZR.Util.Date.getDate(a);a.setTime(a.valueOf()+864E5);var b=a.getFullYear(),b=b+"-"+LZR.HTML5.Util.format(a.getMonth()+1,2,"0"),b=b+"-",b=b+LZR.HTML5.Util.format(a.getDate(),2,"0"),b=b+" ";return b+=LZR.HTML5.Util.format(a.getHours(),2,"0")};LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.handleTimeToDay=function(a){for(var b="",c=0;8>c;c++)switch(b+=a[c],c){case 3:case 5:b+="-"}return b};
LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.creWindSQL=function(){var a=[],b;b="?model=naqpms&isAverage=true&prediction=1&z=1&zone=";var c=this.foc.area.replace(/^d0/,"");b=b+c+"&pTime=";c=this.handleTimeToWindHour(this.foc.tim);b+=c;var c=LZR.Util.Date.getDate(c).valueOf(),d=1;if(this.data.cur.timeStep)switch(this.data.cur.timeStep.id){case "hour":d=1;break;case "day":d=24}for(var g=0;g<this.foc.end-this.foc.start;g+=d){var j=new Date(c+36E5*g),e=b+"&cTime=",e=e+j.getFullYear(),e=e+"-",e=e+LZR.HTML5.Util.format(j.getMonth()+
1,2,"0"),e=e+"-",e=e+LZR.HTML5.Util.format(j.getDate(),2,"0"),e=e+" ",e=e+LZR.HTML5.Util.format(j.getHours(),2,"0");a.push(e)}return a};LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.callback=function(){this.foc.setEventObj(this);this.foc.event.close.append(this.handleClose)};
LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.handleClose=function(a){var b=this.layers[this.index];this.index++;this.qry();switch(b.className){case "LZR.HTML5.Bp.AirqMg.RegStat2.OlLayer":a=this.createBack(this.backImg,a);break;case "LZR.HTML5.Bp.AirqMg.RegStat2.OlGeoJsonLayer":a=this.createBack(this.backJson,a);break}b.info.set(a)};
LZR.HTML5.Bp.AirqMg.RegStat2.Query.prototype.createBack=function(a,b){var c={},d,g,j=this.foc.end-this.foc.start,e=this.data.getStartTimeByTimeAxis();if(this.data.cur.timeStep)switch(this.data.cur.timeStep.id){case "hour":g=1;break;case "day":g=24}for(d=0;d<j;d+=g){var k=new Date(e+36E5*d),f=new LZR.HTML5.Bp.Util.CatchImgByWebsocket.Result({ret:a}),h=k.getFullYear(),i=h;f.tim=h;f.tim+="-";h=LZR.HTML5.Util.format(k.getMonth()+1,2,"0");i+=h;f.tim+=h;f.tim+="-";h=LZR.HTML5.Util.format(k.getDate(),2,
"0");i+=h;f.tim+=h;"hour"==this.data.cur.timeStep.id&&(f.tim+=" ",h=LZR.HTML5.Util.format(k.getHours(),2,"0"),i+=h,f.tim+=h,f.tim+="\u65f6");c[i]=f}for(d=0;d<b.length;d++)c[b[d].tim]&&(c[b[d].tim].ret=b[d].ret);g=[];for(d in c)g.push(c[d]);return g};
