LZR.HTML5.loadJs([LZR.HTML5.jsPath+"util/Layer.js",LZR.HTML5.jsPath+"util/Graphics.js",LZR.HTML5.jsPath+"HTML5/util/Css.js",LZR.HTML5.jsPath+"HTML5/util/Ajax.js",LZR.HTML5.jsPath+"HTML5/Bp/AirqMg/RegStat2.js"]);
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer=function(a){var b=LZR.Util.ValCtrl;LZR.Util.Layer.call(this);this.windUrl=this.map=null;this.cav=document.createElement("canvas");this.ctx=this.cav.getContext("2d");this.data=[];this.timeId=new b(0);this.column=new b(15);this.row=new b(10);this.pad=new b(10);this.length=new b(3);this.color=new b("yellow");this.miniSpeed=new b(0.2);this.autoFlush=!0;this.mapProjection=this.dataProjection="EPSG:4326";this.gp=new LZR.Util.Graphics;this.countOfFlush=0;this.newData=
null;this.event={flushed:new LZR.Util.CallBacks(this)};this.callback();a&&(LZR.setObj(this,a),a.windCanvasStyle&&this.setWindCanvasStyle(a.windCanvasStyle))};LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype=LZR.createPrototype(LZR.Util.Layer.prototype);LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype._super=LZR.Util.Layer.prototype;LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.className="LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer";LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.version="0.0.2";
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.init=function(a){this.map||(this.map=a,a.on("postcompose",LZR.bind(this,this.draw)),a.on("moveend",LZR.bind(this,this.flushNoEvent)),a.getViewport().appendChild(this.cav),this.resize());this.dataProj=ol.proj.get(this.dataProjection);this.mapProj=ol.proj.get(this.mapProjection);this.LLC=ol.proj.get("EPSG:4326")};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.flush=function(a){!1!==a&&(a=!0);this.countOfFlush++;if(this.info.val&&this.visible.val&&0<this.alpha.val&&0<this.row.val&&0<this.column.val){var b=this.info.val[this.timeId.val];if(b){this.queryData(b,a);return}}this.event.flushed.enableEvent=a;this.flushed();this.draw()};LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.flushNoEvent=function(){this.flush(!1)};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.setWindCanvasStyle=function(a){LZR.HTML5.Util.Css.addClass(this.cav,a);this.resize()};LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.setWindUrl=function(a){this.windUrl=a};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.queryData=function(a,b){var c=this.windUrl+a,c=c+"&rowNo="+this.column.val,c=c+"&columnNo=",c=c+this.row.val,d=this.pad.val,f=ol.proj.transform(this.map.getCoordinateFromPixel([d,d]),this.mapProj,this.LLC),d=ol.proj.transform(this.map.getCoordinateFromPixel([this.cav.clientWidth-d,this.cav.clientHeight-d]),this.mapProj,this.LLC),c=c+("&lonmin="+f[0]),c=c+("&latmin="+d[1]),c=c+("&lonmax="+d[0]),c=c+("&latmax="+f[1]);(new LZR.HTML5.Util.Ajax).get(c,LZR.bind(this,
this.onload,b))};LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.handleWindData=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],f=Math.sqrt(d[3]*d[3]+d[2]*d[2]);if(f>this.miniSpeed.val){var e=0;0===d[2]?e=0<d[3]?-Math.PI/2:Math.PI/2:(e=Math.atan(-d[3]/d[2]),0>d[2]&&(e+=Math.PI));e=this.gp.calcTransform(e,1,1,0,0);d=ol.proj.transform([d[0],d[1]],this.dataProj,this.mapProj);b.push([e,this.length.val*f,d])}}return b};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.draw=function(){this.ctx.clearRect(0,0,this.cav.width,this.cav.height);if(this.visible.val&&0<this.alpha.val&&this.data){this.ctx.save();this.ctx.strokeStyle=this.color.val;this.ctx.globalAlpha=this.alpha.val;this.ctx.beginPath();for(var a=0;a<this.data.length;a++){var b=this.data[a],c=b[0],d=this.map.getPixelFromCoordinate(b[2]);this.ctx.setTransform(c[0],c[1],c[2],c[3],d[0],d[1]);this.drowArrow(b[1]);this.ctx.closePath()}this.ctx.stroke();this.ctx.restore()}};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.drowArrow=function(a){var b=a-this.length.val;this.ctx.moveTo(0,0);this.ctx.lineTo(a,0);this.ctx.lineTo(b,a-b);this.ctx.moveTo(a,0);this.ctx.lineTo(b,b-a)};LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.drowArrow1=function(a){var b=0.2*a;this.ctx.moveTo(0,0);this.ctx.lineTo(a,0);this.ctx.moveTo(a,0);this.ctx.lineTo(0,b);this.ctx.lineTo(b,0);this.ctx.lineTo(0,-b)};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.flushed=function(){this.countOfFlush--;return this.event.flushed.execute(this)};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.callback=function(){this.timeId.setEventObj(this);this.timeId.event.change.append(this.flush);this.info.setEventObj(this);this.info.event.set.append(this.flush);this.alpha.setEventObj(this);this.alpha.event.change.append(this.draw);this.visible.setEventObj(this);this.visible.event.change.append(this.flushNoEvent);this.column.setEventObj(this);this.column.event.change.append(this.flushNoEvent);this.row.setEventObj(this);this.row.event.change.append(this.flushNoEvent);
this.pad.setEventObj(this);this.pad.event.change.append(this.flushNoEvent);this.length.setEventObj(this);this.length.event.change.append(this.draw);this.color.setEventObj(this);this.color.event.change.append(this.draw);LZR.HTML5.Util.Event.addEvent(window,"resize",LZR.bind(this,this.resize),!1)};
LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.onload=function(a,b){b&&(this.newData=this.handleWindData(JSON.parse(b)),this.autoFlush&&(this.data=this.newData,this.draw()));this.event.flushed.enableEvent=a;this.flushed()};LZR.HTML5.Bp.AirqMg.RegStat2.WindLayer.prototype.resize=function(){this.cav.width=this.cav.clientWidth;this.cav.height=this.cav.clientHeight};
