window.THREE||LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/expand/threejs/three.min.js",LZR.HTML5.jsPath+"HTML5/expand/threejs/OBJLoader.js",LZR.HTML5.jsPath+"HTML5/expand/threejs/TrackballControls.js"]);LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/util/Util.js"]);
LZR.HTML5.WebGL.Three.Ball3D=function(a){this.canvas=null;this.height=this.width=0;this.renderer=null;this.backColor=isNaN(a.backColor)?13421772:a.backColor;this.near=0.01;this.far=1E5;this.mod=this.camera=this.scene=null;this.meshs={};this.controls=this.light=null;this.center=a.center?new THREE.Vector3(a.center.x,a.center.y,a.center.z):new THREE.Vector3(0,0,0);this.rotateId=0;this.testLine=[];this.init(a)};LZR.HTML5.WebGL.Three.Ball3D.prototype.className="LZR.HTML5.WebGL.Three.Ball3D";
LZR.HTML5.WebGL.Three.Ball3D.prototype.version="0.0.2";
LZR.HTML5.WebGL.Three.Ball3D.prototype.init=function(a){this.createRanderer(a);this.scene=new THREE.Scene;this.mod=new THREE.Object3D;this.scene.add(this.mod);a.fov?this.camera=new THREE.PerspectiveCamera(a.fov,this.width/this.height,this.near,this.far):(this.near=-this.far,this.camera=new THREE.OrthographicCamera(this.width/-2,this.width/2,this.height/2,this.height/-2,this.near,this.far),a.zoom&&(this.camera.zoom=a.zoom,this.camera.updateProjectionMatrix()));this.scene.add(this.camera);a.cameraPosition?
this.camera.position.set(a.cameraPosition.x,a.cameraPosition.y,a.cameraPosition.z):this.camera.position.set(0,0,1);var b=new THREE.AmbientLight(394758);this.scene.add(b);this.light=new THREE.DirectionalLight(16777215);this.light.position.copy(this.camera.position);this.scene.add(this.light);this.controls=new THREE.TrackballControls(this.camera,this.canvas);a.minCtrlDistance&&(this.controls.minDistance=a.minCtrlDistance);a.maxCtrlDistance&&(this.controls.maxDistance=a.maxCtrlDistance);this.control();
a.file&&this.load3D(a.file)};LZR.HTML5.WebGL.Three.Ball3D.prototype.createRanderer=function(a){a.canvas?(this.canvas=a.canvas,this.width=this.canvas.width,this.height=this.canvas.height,this.renderer=new THREE.WebGLRenderer({canvas:a.canvas})):(this.renderer=new THREE.WebGLRenderer,this.canvas=this.renderer.domElement,a.width&&a.height&&renderer.setSize(a.width,a.height),this.width=this.canvas.width,this.height=this.canvas.height);this.renderer.setClearColor(this.backColor)};
LZR.HTML5.WebGL.Three.Ball3D.prototype.load3D=function(a){switch(LZR.HTML5.Util.getFileExtension(a)){case "obj":this.loadObj(a);break;default:this.loadJson(a)}};LZR.HTML5.WebGL.Three.Ball3D.prototype.appendMesh=function(a,b){this.meshs[a]=b;this.mod.add(b);this.flush()};LZR.HTML5.WebGL.Three.Ball3D.prototype.removeMesh=function(a){this.mod.remove(this.meshs[a]);this.flush()};
LZR.HTML5.WebGL.Three.Ball3D.prototype.loadJson=function(a){(new THREE.JSONLoader).load(a,LZR.HTML5.Util.bind(this,function(b,d){for(var c=0;c<d.length;c++)d[c].side=THREE.DoubleSide;c=new THREE.MeshFaceMaterial(d);c=new THREE.Mesh(b,c);this.meshs[a]=c;this.mod.add(c);this.flush()}))};
LZR.HTML5.WebGL.Three.Ball3D.prototype.loadObj=function(a){(new THREE.OBJLoader).load(a,LZR.HTML5.Util.bind(this,function(b){b.traverse(function(a){a instanceof THREE.Mesh&&(a.material.side=THREE.DoubleSide)});this.meshs[a]=b;this.mod.add(b);this.flush()}))};LZR.HTML5.WebGL.Three.Ball3D.prototype.rotate=function(){this.rotateId=setInterval(LZR.HTML5,Util.bind(this,function(){this.mod.rotation.y+=0.01;this.mod.rotation.y>2*Math.PI&&(this.mod.rotation.y-=2*Math.PI);this.flush()}),20)};
LZR.HTML5.WebGL.Three.Ball3D.prototype.stopRotate=function(){clearInterval(this.rotateId)};LZR.HTML5.WebGL.Three.Ball3D.prototype.control=function(){requestAnimationFrame(LZR.HTML5.Util.bind(this,this.control));this.controls.update();this.flush()};LZR.HTML5.WebGL.Three.Ball3D.prototype.flush=function(){this.renderer.render(this.scene,this.camera)};
