LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/WebGL/THREE/Ball3D.js",LZR.HTML5.jsPath+"HTML5/WebGL/THREE/PositionBox.js",LZR.HTML5.jsPath+"HTML5/util/Scroll.js",LZR.HTML5.jsPath+"HTML5/util/Event.js"]);
LZR.HTML5.WebGL.Three.BoxMap=function(){this.map={w:1E3,h:1E3,data:"data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=",obj:null};this.box={minlon:0,minlat:0,maxlon:0,maxlat:0,top:250,left:250,w:500,h:500,z:300,obj:null,ctrl:null};this.center=this.view=this.cav=null;this.max=this.min=0};LZR.HTML5.WebGL.Three.BoxMap.prototype.className="LZR.HTML5.WebGL.Three.BoxMap";LZR.HTML5.WebGL.Three.BoxMap.prototype.version="0.0.3";
LZR.HTML5.WebGL.Three.BoxMap.prototype.initMap=function(){this.max=this.map.w<this.map.h?this.map.h:this.map.w;this.max<this.box.z&&(this.max=this.box.z);this.center={x:this.box.left+this.box.w/2,y:this.box.top+this.box.h/2,z:0};this.min=this.center.x<this.center.y?this.center.x:this.center.y;this.map.h-this.center.y<this.min&&(this.min=this.map.h-this.center.y);var a=new THREE.PlaneGeometry(this.map.w,this.map.h);a.vertices[0].x=-this.center.x;a.vertices[0].y=this.center.y;a.vertices[1].x=this.map.w-
this.center.x;a.vertices[1].x<this.min&&(this.min=a.vertices[1].x);a.vertices[1].y=this.center.y;a.vertices[2].x=-this.center.x;a.vertices[2].y=this.center.y-this.map.h;a.vertices[3].x=this.map.w-this.center.x;a.vertices[3].y=this.center.y-this.map.h;this.map.obj=new THREE.Mesh(a,new THREE.MeshBasicMaterial({map:THREE.ImageUtils.loadTexture(this.map.data),side:THREE.DoubleSide}))};
LZR.HTML5.WebGL.Three.BoxMap.prototype.initBox=function(a){this.box.obj=new LZR.HTML5.WebGL.Three.PositionBox({x:0,y:0,lat:this.box.minlat+(this.box.maxlat-this.box.minlat)/2,lng:this.box.minlon+(this.box.maxlon-this.box.minlon)/2,min:1,max:this.min,imgUrl:{}});this.box.obj.init(this.box.w/2,this.box.h/2,this.box.z,a);this.box.obj.create()};
LZR.HTML5.WebGL.Three.BoxMap.prototype.initCav=function(a){this.wb=new LZR.HTML5.WebGL.Three.Ball3D({fov:75,minCtrlDistance:10,maxCtrlDistance:this.max,backColor:a,canvas:this.cav});this.wb.appendMesh("map",this.map.obj);this.wb.appendMesh("box",this.box.obj.create())};
LZR.HTML5.WebGL.Three.BoxMap.prototype.initCtrl=function(a,c,e){this.view=a;this.box.ctrl={top:"\u4e0a",east:"\u4e1c",south:"\u5357",west:"\u897f",north:"\u5317"};var f=function(a,b){a.setAlpha(b/100)},b,d;for(b in this.box.ctrl)d=this.box.ctrl[b],this.box.ctrl[b]=new LZR.HTML5.Util.Scroll({count:100,position:100*this.box.obj[b].getAlpha(),direction:2,autoLen:1,autoMin:30,padd:0,len:"100%",stripClass:c,btnClass:e,div:a}),this.box.ctrl[b].btn.innerHTML=d,this.box.ctrl[b].init(),this.box.ctrl[b].ctrlEnable(),
this.box.ctrl[b].onchange=LZR.bind(this,f,this.box.obj[b])};
LZR.HTML5.WebGL.Three.BoxMap.prototype.init=function(a){isNaN(a.mapW)||(this.map.w=a.mapW);isNaN(a.mapH)||(this.map.h=a.mapH);a.mapData&&(this.map.data=a.mapData);isNaN(a.boxMinlon)||(this.box.minlon=a.boxMinlon);isNaN(a.boxMinlat)||(this.box.minlat=a.boxMinlat);isNaN(a.boxMaxlon)||(this.box.maxlon=a.boxMaxlon);isNaN(a.boxMaxlat)||(this.box.maxlat=a.boxMaxlat);isNaN(a.boxTop)||(this.box.top=a.boxTop);isNaN(a.boxLeft)||(this.box.left=a.boxLeft);isNaN(a.boxW)||(this.box.w=a.boxW);isNaN(a.boxH)||(this.box.h=
a.boxH);isNaN(a.boxZ)||(this.box.z=a.boxZ);isNaN(a.alpha)&&(a.alpha=0.4);a.backColor||(a.backColor=0);a.cav?this.cav=a.cav:(this.cav=document.createElement("canvas"),this.cav.width=800,this.cav.height=600,a.div&&(this.cav.style.width="100%",this.cav.style.height="100%",a.div.appendChild(this.cav),this.cav.width=this.cav.clientWidth,this.cav.height=this.cav.clientHeight));LZR.HTML5.Util.Event.addEvent(window,"resize",LZR.bind(this,function(){this.cav.width=this.cav.clientWidth;this.cav.height=this.cav.clientHeight}),
!1);this.initMap();this.initBox(a.alpha);this.initCav(a.backColor)};LZR.HTML5.WebGL.Three.BoxMap.prototype.setAlpha=function(a,c){this.box.ctrl?this.box.ctrl[a].setPosition(100*c):this.box.obj[a].setAlpha(c)};
LZR.HTML5.WebGL.Three.BoxMap.prototype.setCamera=function(a){switch(a){case "top":this.wb.camera.up.x=0;this.wb.camera.up.y=1;this.wb.camera.up.z=0;this.wb.camera.position.set(0,0,this.max/1.5);break;case "east":this.wb.camera.up.x=-1;this.wb.camera.up.y=0;this.wb.camera.up.z=0;this.wb.camera.position.set(this.max/1.5,0,this.max/5);break;case "west":this.wb.camera.up.x=1;this.wb.camera.up.y=0;this.wb.camera.up.z=0;this.wb.camera.position.set(-this.max/1.5,0,this.max/5);break;case "south":this.wb.camera.up.x=
0;this.wb.camera.up.y=1;this.wb.camera.up.z=0;this.wb.camera.position.set(0,-this.max/1.5,this.max/5);break;case "north":this.wb.camera.up.x=0,this.wb.camera.up.y=-1,this.wb.camera.up.z=0,this.wb.camera.position.set(0,this.max/1.5,this.max/5)}};
LZR.HTML5.WebGL.Three.BoxMap.prototype.flush=function(a){a.top&&(this.box.obj.top.imgUrl=a.top);a.east&&(this.box.obj.east.imgUrl=a.east);a.south&&(this.box.obj.south.imgUrl=a.south);a.west&&(this.box.obj.west.imgUrl=a.west);a.north&&(this.box.obj.north.imgUrl=a.north);this.box.obj.flush();a.map&&(this.map.obj.material.map=THREE.ImageUtils.loadTexture(a.map),this.map.data=a.map)};
