LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/expand/threejs/three.js",LZR.HTML5.jsPath+"HTML5/util/Util.js",LZR.HTML5.jsPath+"HTML5/util/MouseDropController.js",LZR.HTML5.jsPath+"util/Graphics/CoordinateChange.js"]);
LZR.HTML5.WebGL.Three.OrthographicControl=function(a){LZR.HTML5.Util.MouseDropController.call(this,a.ctrlDom);this.camera=a.camera;this.lights=a.light?"Array"==LZR.HTML5.Util.getClassName(a.light)?a.light:[a.light]:[];this.center=a.center?new THREE.Vector3(a.center.x,a.center.y,a.center.z):new THREE.Vector3(0,0,0);this.zoomScale=0.1;this.moveScale=1;this.rotateScale=3;this.resetter={x:null,y:null,z:null,position:null,up:null,zoom:0,lights:LZR.HTML5.Util.clone(this.lights)};this.rigid={x:new THREE.Vector3(1,
0,0),y:new THREE.Vector3(0,1,0),z:new THREE.Vector3(0,0,-1),look:this.center.clone(),position:this.camera.position.clone()};this.cc=null;this.distance=1;this.ball=null;this.init(a)};LZR.HTML5.WebGL.Three.OrthographicControl.prototype=LZR.createPrototype(LZR.HTML5.Util.MouseDropController.prototype);LZR.HTML5.WebGL.Three.OrthographicControl.prototype.className="LZR.HTML5.WebGL.Three.OrthographicControl";LZR.HTML5.WebGL.Three.OrthographicControl.prototype.version="0.0.3";
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.init=function(){this.initCamera()};
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.initCamera=function(){this.camera.position.set(0,0,0);this.camera.up.copy(this.rigid.y);this.camera.lookAt(this.rigid.z);this.camera.position.copy(this.rigid.position);var a=this.center.clone().sub(this.rigid.position);this.distance=a.length();var b=new THREE.Vector3(0,0,-this.distance),e=Math.acos(b.dot(a)/b.length()/this.distance);if(e){var d=new THREE.Vector3,c=new THREE.Quaternion;d.crossVectors(b,a).normalize();c.setFromAxisAngle(d,e);this.rigid.x.applyQuaternion(c);
this.rigid.y.applyQuaternion(c);this.rigid.z.applyQuaternion(c);this.camera.up.copy(this.rigid.y)}this.rigid.x.add(this.rigid.position);this.rigid.y.add(this.rigid.position);this.rigid.z.add(this.rigid.position);this.camera.lookAt(this.rigid.look);this.resetter.position=this.camera.position.clone();this.resetter.up=this.camera.up.clone();this.resetter.x=this.rigid.x.clone();this.resetter.y=this.rigid.y.clone();this.resetter.z=this.rigid.z.clone();"OrthographicCamera"==this.camera.type&&(this.resetter.zoom=
this.camera.zoom)};
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.zoom=function(){var a=(this.midStart.y-this.midEnd.y)/10+this.wheelValue;if(a)if(this.wheelValue=0,this.midStart=LZR.HTML5.Util.clone(this.midEnd),"OrthographicCamera"==this.camera.type)a=0<a?1+a*this.zoomScale:1/(1-a*this.zoomScale),this.camera.zoom*=a,this.camera.updateProjectionMatrix();else{a*=-1;a=0<a?1+a*this.zoomScale:1/(1-a*this.zoomScale);this.rigid.look.sub(this.center).multiplyScalar(a).add(this.center);var b=this.rigid.position.clone();b.sub(this.center).multiplyScalar(a).add(this.center).sub(this.rigid.position);
this.rigid.position.add(b);this.rigid.x.add(b);this.rigid.y.add(b);this.rigid.z.add(b);this.camera.position.copy(this.rigid.position);this.distance=this.rigid.position.distanceTo(this.rigid.look);this.cc&&(LZR.HTML5.Util.del(this.cc),this.cc=null)}};
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.pan=function(){var a=this.rightStart.x-this.rightEnd.x,b=this.rightEnd.y-this.rightStart.y;if(a||b)a=new THREE.Vector3(a,b,0),"OrthographicCamera"==this.camera.type?a.multiplyScalar(this.moveScale/this.camera.zoom):a.multiplyScalar(this.moveScale*this.distance/360),this.cc||(this.cc=new LZR.Util.Graphics.CoordinateChange({s:{p1:{x:0,y:0,z:0},p2:{x:1,y:0,z:0},p3:{x:0,y:1,z:0},p4:{x:0,y:0,z:-1}},t:{p1:this.rigid.position,p2:this.rigid.x,p3:this.rigid.y,
p4:this.rigid.z},scale:1}),this.cc.computeR4(),this.cc.p=this.rigid.position.clone()),this.cc.trans(a,a),a.sub(this.cc.p),this.rigid.position.add(a),this.rigid.look.add(a),this.rigid.x.add(a),this.rigid.y.add(a),this.rigid.z.add(a),this.camera.position.copy(this.rigid.position),this.rightStart=LZR.HTML5.Util.clone(this.rightEnd)};
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.rotate=function(){this.ball||(this.ball=LZR.HTML5.Util.getDomPositionForDocument(this.ctrlDom));if(this.leftStart.x-this.leftEnd.x||this.leftEnd.y-this.leftStart.y){var a=this.getCoordinateOnBall(this.leftEnd),b=this.getCoordinateOnBall(this.leftStart),e=Math.acos(a.dot(b)/a.length()/b.length());if(e){var d=new THREE.Vector3,c=new THREE.Quaternion;d.crossVectors(a,b).normalize();this.cc||(this.cc=new LZR.Util.Graphics.CoordinateChange({s:{p1:{x:0,
y:0,z:0},p2:{x:1,y:0,z:0},p3:{x:0,y:1,z:0},p4:{x:0,y:0,z:-1}},t:{p1:this.rigid.position,p2:this.rigid.x,p3:this.rigid.y,p4:this.rigid.z},scale:1}),this.cc.computeR4(),this.cc.p=this.rigid.position.clone());this.cc.trans(d,d);d.sub(this.cc.p).normalize();e*=this.rotateScale;c.setFromAxisAngle(d,e);for(b in this.rigid)this.rigid[b].sub(this.center);for(b in this.lights)this.lights[b].position.sub(this.center);for(b in this.rigid)this.rigid[b].applyQuaternion(c);for(b in this.lights)this.lights[b].position.applyQuaternion(c);
this.camera.up.applyQuaternion(c);for(b in this.rigid)this.rigid[b].add(this.center);for(b in this.lights)this.lights[b].position.add(this.center);this.camera.position.copy(this.rigid.position);this.camera.lookAt(this.rigid.look);LZR.HTML5.Util.del(this.cc);this.cc=null;this.cc=new LZR.Util.Graphics.CoordinateChange({s:{p1:{x:0,y:0,z:0},p2:{x:1,y:0,z:0},p3:{x:0,y:1,z:0},p4:{x:0,y:0,z:-1}},t:{p1:this.rigid.position,p2:this.rigid.x,p3:this.rigid.y,p4:this.rigid.z},scale:1});this.cc.computeR4();this.cc.p=
this.rigid.position.clone()}this.leftStart=LZR.HTML5.Util.clone(this.leftEnd)}};LZR.HTML5.WebGL.Three.OrthographicControl.prototype.getCoordinateOnBall=function(a){var a=new THREE.Vector3(2*((a.x-this.ball.left)/this.ball.width)-1,2*((this.ball.top-a.y)/this.ball.height)+1,0),b=a.length();1>b?a.z=Math.sqrt(1-b*b):a.normalize();return a};
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.update=function(){switch(this.state){case this.STATE.LEFT:this.rotate();break;case this.STATE.MID:this.zoom();break;case this.STATE.RIGHT:this.pan();break;case this.STATE.NONE:this.zoom()}};
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.reset=function(){this.camera.zoom=this.resetter.zoom;this.camera.up.copy(this.resetter.up);this.camera.position.copy(this.resetter.position);this.camera.lookAt(this.center);this.rigid.x.copy(this.resetter.x);this.rigid.y.copy(this.resetter.y);this.rigid.z.copy(this.resetter.z);this.rigid.look.copy(this.center);this.rigid.position.copy(this.resetter.position);for(var a in this.lights)this.lights[a].position.copy(this.resetter.lights[a].position)};
LZR.HTML5.WebGL.Three.OrthographicControl.prototype.autoFlush=function(){};
