window.ol||(LZR.HTML5.loadJs([LZR.HTML5.jsPath+"HTML5/expand/ol3/ol.js"]),LZR.HTML5.loadCss([LZR.HTML5.jsPath+"HTML5/expand/ol3/ol.css"]));
LZR.HTML5.Bp.OpenLayers.Orbit=function(a){a.map&&(this.map=a.map,this.initData(a.data),this.sourceColor=a.sourceColor?a.sourceColor:"red",this.sourceSize=a.sourceSize?a.sourceSize:20,this.sourceWidth=a.sourceWidth?a.sourceWidth:2,this.sourceSpeed=a.sourceSpeed?a.sourceSpeed:0.01,this.orbitAnimationColor=this.initColor(a.orbitAnimationColor),this.orbitShadowColor=this.initColor(a.orbitShadowColor),this.orbitColor=this.initColor(a.orbitColor),this.orbitBlur=a.orbitBlur?a.orbitBlur:20,this.orbitScale=
a.orbitScale?a.orbitScale:0.5,this.orbitSpeed=a.orbitSpeed?a.orbitSpeed:0.01,this.nodeShadowColor=a.nodeShadowColor?a.nodeShadowColor:this.orbitShadowColor,this.nodeColor=a.nodeColor?a.nodeColor:this.orbitColor,this.nodeBlur=a.nodeBlur?a.nodeBlur:this.orbitBlur,this.nodeScale=a.nodeScale?a.nodeScale:3E3,this.nodeMax=a.nodeMax?a.nodeMax:8,this.nodeMin=a.nodeMin?a.nodeMin:6,a.showNode?this.setShowNode(a.showNode):this.setShowNode(0),this.title=a.title?a.title:document.createElement("div"),this.titleArea=
a.titleArea?a.titleArea:0,this.curentPosition=[-1,-1],this.nodeOverIndex=this.orbitOverIndex=-1,this.ctx=this.canvas=this.layer=null)};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.className="LZR.HTML5.Bp.OpenLayers.Orbit";LZR.HTML5.Bp.OpenLayers.Orbit.prototype.version="0.0.3";
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.initColor=function(a){var b=0,c=[];if(a){if("string"==LZR.HTML5.Util.getClassName(a)){for(b=0;b<this.data.length;b++)c.push(a);return c}c=a;b=c.length;isNaN(b)&&(b=0)}for(;b<this.data.length;b++)a="rgba("+Math.floor(255*Math.random())+", "+Math.floor(255*Math.random())+", "+Math.floor(255*Math.random())+", 1)",c.push(a);return c};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.init=function(){null===this.layer&&(this.layer=new ol.layer.Image({source:new ol.source.ImageStatic({url:"",imageExtent:[0,0,0,0]})}),this.map.on("pointermove",LZR.bind(this,function(a){this.curentPosition=a.pixel})),this.layer.on("postcompose",LZR.bind(this,function(a){if(null===this.ctx){
	
				this.canvas = document.createElement("canvas");
				this.map.getViewport().appendChild(this.canvas);
				this.canvas.style.width = "100%";
				this.canvas.style.height = "100%";
				this.canvas.style.position = "absolute";
				this.canvas.style.top = "0";
				this.canvas.style.left = "0";
				this.canvas.width = this.canvas.clientWidth;
				this.canvas.height = this.canvas.clientHeight;
				this.ctx = this.canvas.getContext("2d");

	var b=this.title.style;b.visibility="hidden";b.position="relative";b=this.map.getTargetElement();b.appendChild(this.title);
this.mapW=b.scrollWidth;this.mapH=b.scrollHeight;this.titleNdi=this.titleObi=-1}this.flush(this.ctx)&&this.map.render()})),this.map.addLayer(this.layer))};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.flush=function(a){a.clearRect(0,0,this.canvas.width,this.canvas.height);var b=this.map.getView().getResolution();this.calcNodeWidth(b);this.nodeOverIndex=this.orbitOverIndex=-1;for(var c=!1,e=0;e<this.data.length;e++)if(this.data[e].visible){var c=!0,f=this.data[e].nodes;this.calcData(f,b);this.drawOrbitPath(f,a,e);this.calcNode(f,a,e);if(this.orbitOverIndex===e){if(this.drawNode(f,a,e),0<=this.nodeOverIndex&&(this.titleObi!==this.orbitOverIndex||this.titleNdi!==this.nodeOverIndex)){this.titleObi=this.orbitOverIndex;
this.titleNdi=this.nodeOverIndex;var d=this.title.style;d.left=this.curentPosition[0]+"px";d.top=this.curentPosition[1]-this.mapH+"px";this.onShowTitle(this.title,f[this.titleNdi],this.titleObi,this.titleNdi);"hidden"===d.visibility&&(d.visibility="visible")}}else this.ap[e]+=this.orbitSpeed,1<this.ap[e]&&(this.ap[e]=0);this.drawOrbit(f,a,e)}c&&(this.drawSource(a),-1!==this.titleNdi&&-1===this.nodeOverIndex&&(this.titleNdi=this.titleObi=-1,this.title.style.visibility="hidden"));return c};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.initData=function(a){this.data=[];this.ap=[];if(a)for(var b=0;b<a.length;b++){var c={visible:!0};c.zlevel=a[b].zlevel;c.nodes=[];for(var e=a[b].grdCollection,f=0;f<e.length;f++){var d={},g;for(g in e[f])d[g]=e[f][g];d.lon=e[f].x;d.lat=e[f].y;if(0<f){var h=c.nodes[f-1],j=d.y-h.y,k=d.x-h.x;h.lineAngle=Math.asin(j/Math.sqrt(j*j+k*k));0>k&&(h.lineAngle=Math.PI-h.lineAngle)}c.nodes.push(d)}this.data.push(c);this.ap.push(0)}};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcNodeWidth=function(a){this.nodeWidth=this.nodeScale/a;this.nodeWidth>this.nodeMax?this.nodeWidth=this.nodeMax:this.nodeWidth<this.nodeMin&&(this.nodeWidth=this.nodeMin)};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcData=function(a,b){for(var c=0,e=0;e<a.length;e++){var f=a[e],d=this.calcPixel(f.lon,f.lat);f.x=d[0];f.y=d[1];f.u=f.su/b*this.windScale;f.v=f.sv/b*this.windScale;if(0<e){var d=a[e-1],g=f.y-d.y,f=f.x-d.x;d.lineLong=Math.sqrt(g*g+f*f);d.lineAngle=Math.asin(g/d.lineLong);0>f&&(d.lineAngle=Math.PI-d.lineAngle);d.lineLong>c&&(c=d.lineLong)}}a.max=c};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawOrbitPath=function(a,b,c){var e=this.nodeWidth*this.orbitScale;b.save();b.fillStyle=this.orbitColor[c];b.shadowColor=this.orbitShadowColor[c];b.shadowBlur=this.orbitBlur;b.beginPath();for(var f=0;f<a.length-1;f++){var d=this.calcTransform(a[f].lineAngle,1,1,a[f].x,a[f].y);b.setTransform(d[0],d[1],d[2],d[3],d[4],d[5]);b.moveTo(0,e);b.arc(0,0,e,Math.PI/2,3*Math.PI/2);b.lineTo(a[f].lineLong,-e);b.arc(a[f].lineLong,0,e,-Math.PI/2,Math.PI/2);b.closePath()}b.fill();
b.restore();-1===this.orbitOverIndex&&b.isPointInPath(this.curentPosition[0],this.curentPosition[1])&&(this.orbitOverIndex=c)};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcNode=function(a,b,c){for(var e=this.nodeWidth+this.titleArea,f=2*Math.PI,d=0;d<a.length;d++)if(b.beginPath(),b.arc(a[d].x,a[d].y,e,0,f),(-1===this.orbitOverIndex||this.orbitOverIndex===c)&&b.isPointInPath(this.curentPosition[0],this.curentPosition[1])){this.orbitOverIndex=c;this.nodeOverIndex=d;break}};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawNode=function(a,b,c){var e=0,f=a.length;switch(this.showNode){case 1:e++;break;case 2:f--}var d=this.nodeWidth,g=2*Math.PI;b.save();b.fillStyle=this.nodeColor[c];b.shadowColor=this.nodeShadowColor[c];b.shadowBlur=this.nodeBlur;b.beginPath();for(c=e;c<f;c++)b.arc(a[c].x,a[c].y,d,0,g),b.closePath();b.fill();b.restore()};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawOrbit=function(a,b,c){b.save();b.fillStyle=this.orbitAnimationColor[c];b.beginPath();for(i=1;i<a.length;i++){var e=(a[i].x-a[i-1].x)*this.ap[c]+a[i-1].x,f=(a[i].y-a[i-1].y)*this.ap[c]+a[i-1].y,d=0.8*(a[i-1].lineLong/a.max);0.2>d&&(d=0.2);d*=this.nodeWidth;e=this.calcTransform(a[i-1].lineAngle,d,d,e,f);b.setTransform(e[0],e[1],e[2],e[3],e[4],e[5]);b.moveTo(0,0);b.lineTo(-1,1);b.lineTo(3,0);b.lineTo(-1,-1);b.closePath()}b.fill();b.restore()};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.drawSource=function(a){var b,c,e;c=this.data[0].nodes;switch(this.showNode){case 2:e=c.length-1;b=c[e].x;c=c[e].y;0.05>this.apSource&&(this.apSource=1);break;default:b=c[0].x,c=c[0].y,1<this.apSource&&(this.apSource=0.05)}e=this.sourceSize*this.apSource;a.save();a.lineWidth=this.sourceWidth;a.strokeStyle=this.sourceColor;a.beginPath();a.arc(b,c,e,0,2*Math.PI);a.stroke();a.restore();this.apSource+=this.sourceSpeed};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.setVisible=function(a,b){var c=this.data[a];c&&(c.visible=b);b&&this.map.render()};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.setShowNode=function(a){this.showNode=a;2===this.showNode?(this.apSource=1,0<this.sourceSpeed&&(this.sourceSpeed*=-1)):(this.apSource=0,0>this.sourceSpeed&&(this.sourceSpeed*=-1))};
LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcTransform=function(a,b,c,e,f){var d=[];d.push(b*Math.cos(a));d.push(c*Math.sin(a));d.push(-1*b*Math.sin(a));d.push(c*Math.cos(a));d.push(e);d.push(f);return d};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.calcPixel=function(a,b){return this.map.getPixelFromCoordinate(ol.proj.fromLonLat([a,b]))};LZR.HTML5.Bp.OpenLayers.Orbit.prototype.onShowTitle=function(){};
